### ISSUE TITLE
Serving identical content using different URLS - using fonts with Understrap + Elementor Pro

### ISSUE THREAD

**Issue by GJF100** [understrap/understrap#1011]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

**WordPress Version: 5.2.2
**Elementor Pro Version: 2.5.8

I'm using Understrap + Elementor Pro. Both are serving up the same font from different URLs/Folders. Is there a way to solve this such that only one URL for this specific font is used across the website?

Many thanks.

**Comment by Thomas-A-Reinert** [comment]
Ehm, I´m sure there is @GJF100 . But that´s not an UnderStrap problem. 

In my eyes theres a preference (just a PERSONAL opinion!)

- Theme precedes everything (because YOU to be the one and only directive!)
- after that comes everthing else.
- and if you really didn´t get your **** get set up correctly: have the rest an !important

As far as this is not a real UNDERSTRAP issue i´m going to close that issue
