### ISSUE TITLE
Hook.php changes have no effect after update of parent theme 

### ISSUE THREAD

**Issue by frakka92** [understrap/understrap#1100]
## Issue is about..
  - [ ?] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [X ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.3.2
  - **OS Version:** MacOS [ Catalina 10.15.2 ] 
  - **Browser:** [ Chrome Version 79.0.3945.88 (Official Build) (64-bit) ]
  - **Language:** [ all | PHP  7.3.6 ]
  - **Node.js & NPM Versions:** Node.js [V v10.17.0] | NPM [V 6.11.3 ]

---

# Issue Overview for Bugreports
After updating my wordpress project with the latest understrap and understrap-child versions from github, the footer/credits is not customizable anymore. It only works if I edit the hook.php of the parent theme.

## Steps to reproduce?
Update the parent theme.

## *When* does this occur?
Only if update the parent theme. I also have a project  with understrap-child 0.5.3 and i have the same issue. 

## *Where* on the platform does it happen?
Localhost

## *How* do we replicate the issue?
Update the parent theme.

## Screenshots / Video

Hook.php of the child theme
<img width="1680" alt="Screenshot 2019-12-19 at 12 14 08" src="https://user-images.githubusercontent.com/7945479/71170580-e5bda200-225b-11ea-813d-2b6e11064d2c.png">

Hook.php of the parent theme
<img width="1680" alt="Screenshot 2019-12-19 at 12 21 03" src="https://user-images.githubusercontent.com/7945479/71170629-04239d80-225c-11ea-9f61-0caf867d6aa4.png">

**Comment by IanDelMar** [comment]
For now, use `require_once get_stylesheet_directory() . '/inc/hooks.php'` in the functions.php of your child theme. Files from the /inc/ folder are now loaded using [get_template_directory()](https://developer.wordpress.org/reference/functions/get_template_directory/) which always returns the parent theme directory. Before that, they were loaded using [locate_template()](https://developer.wordpress.org/reference/functions/locate_template/) which returns the child theme directory if the required file exists and the parent directory otherwise. See PR #1020 in response to #930.

I made a PR (#1101) to move the add_action outside the if-condition. So you can write your own `understrap_add_site_info()`, put it in a file and require that file once the PR is merged.

**Comment by Thomas-A-Reinert** [comment]
Yip, that sucks, admittedly. Please refer to @IanDelMar ´s solution.
BTW: Forget about the understrap-child solution anyways. It didn´t get updated for AGES.

**Comment by frakka92** [comment]
So should I use only the "main" understrap and customize that?

**Comment by pattonwebz** [comment]
@frakka92 your method seems ok - with basing things from the child theme. Since it's not updated in a long time though it may be out of sync with the parent theme. 

What I suggest you do is you make your own child theme from the latest parent theme. If your not familiar with making a child theme then instead I suggest you take the parent theme and clone it (changing the name and slug) so it's your own.

**Comment by Thomas-A-Reinert** [comment]
@pattonwebz the child theme IS way out of sync! And I can´t see anyone caring bout it.. 
@frakka92 If you´re not comfy with creating your own child themes please take a look at https://www.hostinger.com/tutorials/how-to-create-wordpress-child-theme for example

**Comment by frakka92** [comment]
@pattonwebz 
@Thomas-A-Reinert 
Thanks to you both. I'll think about another solution and take a look at that link. Since the child theme is not up to date, it can cause more issues like the one I opened and it's not ideal to maintain websites.

**Comment by danemorgan** [comment]
This is a couple of years too late to help you, but @bacoords is hard at work getting the child theme up to date. I just wanted to call his attention to this issue for that process.

**Comment by bacoords** [comment]
This should've been fixed in our latest update where we want back to loading inc/ file overrides from the child theme if they exist, correct?

**Comment by danemorgan** [comment]
I'm not sure on the timeline, I thought this might have predated the change that broke inclusion.

I'd like to test the specific case before we move on though.

**Comment by danemorgan** [comment]
This was fixed in the 0.9.6 release
