### ISSUE TITLE
Pagination - Scroll to top when clicked?

### ISSUE THREAD

**Issue by aaronrobb** [understrap/understrap#1111]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [X ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.3.2
  - **Browser:** [Brave/Chrome]

---

Pagination works great. Only issue is that when you click on the next page number, the page reloads but the user stays at the bottom, so you have to scroll up to the top yourself.
Not sure if this is a specific issue to my install, but if not, is there a fix, so we can tell the system to go to top once clicked?

**Comment by Thomas-A-Reinert** [comment]
Just tried on a fresh install to see if that issue is reprocuable. It´s not.
It wouldn´t make any sense anyway according to browser behaviour.

Please try with a fresh install or anything. However, your "problem" can´t be UnderStrap-related.
That´s why i´m going to close this issue. Feel free to re-open if the probem persists.
