### ISSUE TITLE
npm instal failsnpm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`

### ISSUE THREAD

**Issue by darkogerguric** [understrap/understrap#1113]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [* ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.3.2
  - **OS Version:** [ Windows 10] |
  - **Browser:** [ all  ]
  - **Language:** [ all]
  - **Node.js & NPM Versions:** Node.js [v12.14.0 ] | NPM [V6.13.4]

---

Hi I am not able to install understrap, it fails every time.

npm instal failsnpm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`

I am trying from the theme itself or from the child theme downloaded from the website.

Any suggestions?
Thank you in advance.

# Issue Overview for Bugreports
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Darko\AppData\Roaming\npm-cache\_logs\2020-02-10T12_44_57_851Z-debug.log

## Steps to reproduce?

npm install
## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by noelspringer** [comment]
@darkogerguric it looks like you are using UnderStrap 0.9.3.

Have you tried cloning this repo's master branch (which is 0.9.4) and running `npm instsall`?

Cheers

**Comment by darkogerguric** [comment]
Yes, I tried all, fails every time.
After a LOT of fiddling, I managed to get the child theme working, one that I found here on Github.
I edited gulpfile and some other files as described there and it worked.
Very strange.

**Comment by noelspringer** [comment]
@darkogerguric This is the child theme link from the UnderStrap `README.md` file https://github.com/understrap/understrap-child.

Is that the repo you were using which generated the error message you provided? And is the error message only from running `npm install` from the child theme?

**Comment by darkogerguric** [comment]
Yes, that is the one.
After editing the files as described here it worked:
https://github.com/understrap/understrap-child/issues/229#issuecomment-554858596

It never worked for me with Understrap alone, neither installed from wp.org nor downloaded from here.

There was windows-build-tools, node-sass error, all kind of stuff, but most of the time that one from gulp.
Somehow I got it worked after a lot of time yesterday.
I am in a very urgent project where the client insists on using this theme but must say never had issues when used it before on a few occasions...

**Comment by noelspringer** [comment]
OK Glad you got it worked out. On my linux box when I run `npm install` for the child theme the `gulp copy-assets` task uses `understrap` `0.9.1` despite the version being specified as `^0.9.1` in the `package.json` file. This is because the `package-lock.json` specifies `0.9.1` for the `understrap` version.

If you cloned the child theme from the child theme repo and instead ran `npm upgrade`, the caret `^` before the `understrap` version will tell npm to fetch the latest minor version which on npmjs.com is `0.9.3` and that version does generate your error message.

You could also just lock the version of `understrap` in the `package.json` file to `0.9.1` by removing the caret `^` from the version, delete `package.json` and run `npm update`.

If you had a `node-sass` error, it could be due to the version of `node` you are using. I had to revert from 10.x to 8.17.0 for `node-sass` to work. If you are using NVM it's relatively simple to switch `node` versions.

And just to note, this issue is a child theme issue. The child theme has it's own issue tracking system.

Cheers

Another option for you in case you have another project may be to lock the version at

**Comment by darkogerguric** [comment]
Thank you for the explanation, most likely is Node version what made trouble.
I will keep that in mind for the next time.
Thank you for support.

**Comment by ihtishamzahoor** [comment]
Hi, Maybe I am a bit late to this but what worked for me is to put a trailing slash after `${paths.node}`. The `skip-link-focus-fix.js` caused the `npm install` to throw the error. Here is what I replaced.`

	// _s JS files into /src/js
	gulp
		.src(`${paths.node}/undescores-for-npm/js/skip-link-focus-fix.js`)
		.pipe(gulp.dest(`${paths.dev}/js`));

	done();`

**Comment by pegelf** [comment]
> Hi, Maybe I am a bit late to this but what worked for me is to put a trailing slash after `${paths.node}`. The `skip-link-focus-fix.js` caused the `npm install` to throw the error. Here is what I replaced.`
> 
> ```
> // _s JS files into /src/js
> gulp
> 	.src(`${paths.node}/undescores-for-npm/js/skip-link-focus-fix.js`)
> 	.pipe(gulp.dest(`${paths.dev}/js`));
> 
> done();`
> ```

Thank you. I had same problem today with understrap 0.9.4 and your replacement in gulpfile.js in line 208 solved it.
