### ISSUE TITLE
Fix typo in dependencies in package.json

### ISSUE THREAD

**Issue by twiginteractive** [understrap/understrap#1123]
Please replace "undescores-for-npm" with "underscores-for-npm"
(the current is missing an 'r' in the word "underscores" - perhaps this is/was an aliased legacy version, but I would think https://www.npmjs.com/package/underscores-for-npm is correct. 

Looks like #110 noticed this issue but didn't/couldn't fix, probably due to the error in the NPM repo name that is now fixed.

Also, whenever the next minor release is out, could you push to the NPM repo? Looks like 0.9.3 is the latest version there.

**Comment by Thomas-A-Reinert** [comment]
Hi @twiginteractive - I just remember that I "corrected" that years ago. And was told that the version without an "r" is yet correct. Cannot recall why,  never really got a comprehensible info and/or update to that. It just remained the same since then.
Which one is really in use - only @UnderstrapFramework can (?) tell you. I also told him some time ago that the npm repo is outdated. Nothing happened so far though.

**Comment by holger1411** [comment]
There is a typo in the npm pckage name. So "undescores-for-npm" is the "right" one...

**Comment by twiginteractive** [comment]
Ok - looks like both variants are actually in the repo now (same version 1.0.0)
`npm search underscores-for-npm`
with the correct spelling one being dated 12/19/16 vs the incorrect 09/13/16
so I bet you you could correct the typo now, if you wanted to.

Thanks all.

**Comment by Thomas-A-Reinert** [comment]
2016. That´s not a matter of a "typo". That a matter of a lack of the repo owners skills/dedication or whatever. But I can tell - It will not change within the next two years if the repo don´t change it´s owner.
