### ISSUE TITLE
SCSS Compiling error

### ISSUE THREAD

**Issue by gettonet** [understrap/understrap#1172]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report
  - [x] I need help

I use WP compiler plugin to compile scss to css.
But, with this new build with bootstrap 4.5, I constantly get an error that I can't figure out:

scss error: Incompatible units: \"rem\" and \"\".: line: 9 

I cannot even find in which file is it...I assume it's _variables.scss
Help?

**Comment by gaelgerard** [comment]
You should test it with gulp instead of your plugin. It seems you are not following the Documentation guidelines https://understrap.github.io/ to customize your theme.

**Comment by gettonet** [comment]
Thank you kindly for your reply.
The idea is to make changes on the website on remote server. I have no experience with gulp nor linux terminal commands, so I have found this plugin which served me well before this Understrap build with Bootstrap 4.5.
So I thought maybe someone else had the issue. I found a workaround, to compile css on my local machine using software called Koala, and then upload files to server, but it was much simpler(faster) with the plugin.
Is there a way to integrate compiling within the theme itself? Sorry if my questions are beginner-type..

**Comment by IanDelMar** [comment]
WP compiler including scssphp has not been updated since more then 2 years. The included scssphp version is 0.7.6. scssphp is now at v1.1.0. Take look at the [changelog](https://scssphp.github.io/scssphp/docs/changelog.html) what has been fixed since v0.7.6. I guess it was just a matter of time that things start to fail.

**Comment by gettonet** [comment]
Yes, I'm aware of that. Looking for another solution.
If anyone has suggestions how to integrate gulp watch in the theme itself, please give some guidelines.

**Comment by IanDelMar** [comment]
What exactly are you trying to achieve? Isn't local WordPress development an option?

**Comment by gettonet** [comment]
> 
> 
> What exactly are you trying to achieve? Isn't local WordPress development an option?
> 
> EDIT: Why don't you just look for another plugin compiling scss to css?

Nope, it's a live website, and I'd like not to use additional css files.
There are not much plugins that do the job, I tried WP-SCSS but it appears that it requires specific (different) folder structure.
Ideally, I'd like the theme to behave like https://github.com/jasewarner/gulp-wordpress

**Comment by IanDelMar** [comment]
> Nope, it's a live website, and I'd like not to use additional css files.

You wouldn't use additional CSS files but have a local install of WordPress and the theme. You would then compile the .scss files to .css files and upload the updated files to your live website. I can't see any additional css files.

> Ideally, I'd like the theme to behave like https://github.com/jasewarner/gulp-wordpress

Could you be more specific in your comments? The theme provides a couple of gulp tasks which have to be run via the terminal which is exactly what UnderStrap does.

**Comment by gettonet** [comment]
> Could you be more specific in your comments? The theme provides a couple of gulp tasks which have to be run via the terminal which is exactly what UnderStrap does.

I'd like to have a watcher, so when I change anything in scss file, compiling gets triggered, or looking for option that compiling can be triggered manually through WP admin.

**Comment by IanDelMar** [comment]
> > Could you be more specific in your comments? The theme provides a couple of gulp tasks which have to be run via the terminal which is exactly what UnderStrap does.
> 
> I'd like to have a watcher, so when I change anything in scss file, compiling gets triggered, or looking for option that compiling can be triggered manually through WP admin.

UnderStrap provides a watch task just like Gulp+Wordpress does. In both cases you have to use the terminal. Sorry, I still don't get how Gulp+Wordpress fits into the picture of this issue.

As this issue is clearly related to the plugin, why don't you open an issue there? (https://github.com/burlingtonbytes/WP-Compiler/issues) I don't think that many of the contributors here are willing to add functionality that is already included. It's hard to see the point in maintaining 2 things of the same kind because you are not willing to dig into gulp and it's terminal usage. Don't get me wrong but I just have the impression you are asking "us" to put effort into something because Burlington Bytes does not care about WP Compiler anymore and you don't care about the documented usage of UnderStrap and learning how to use a terminal.

However, download my fork of WP Compiler (https://github.com/IanDelMar/WP-Compiler) with updated scssphp and try whether that works for you.

**Comment by gaelgerard** [comment]
> I'd like to have a watcher, so when I change anything in scss file, compiling gets triggered, 

> which is exactly what UnderStrap does

But, and I think it is the same for gulp-wordpress, you have to run it locally in order to use the gulp tools which (AFAIK) you can't install on a remote server (at least not a shared one).

In fact, your SCSS files shouldn't even be on your remote server because after developping locally, a bunch of `gulp` optimisations are runned to provide you all minified css and js files in a `dist` directory which will be your final theme on your remote server WordPress.

You will earn time and usefull knowledge to give a try to command line with npm and Gulp.

**Comment by gettonet** [comment]
Guys, many thanks. Fiddling with gulp is on my learning list, it's just the time that I don't have at the moment. I'm not the person that expects from the others to do my job, I was just looking for some guidelines.

> However, download my fork of WP Compiler (https://github.com/IanDelMar/WP-Compiler) with updated scssphp and try whether that works for you.

I will, thanks again.

**Comment by IanDelMar** [comment]
> I will, thanks again.

Please let me know whether it works!

**Comment by gettonet** [comment]
> Please let me know whether it works!
Works!

**Comment by IanDelMar** [comment]
Great! Please consider to close the issue.
