### ISSUE TITLE
Customising cookie consent on product page ?

### ISSUE THREAD

**Issue by carlo-13** [understrap/understrap#1196]
Hi there.
I want to make some change to the cookie consent checkbox on woocommerce product page ( change the class, and `<p>` to a `<div>`).
_See here: https://imgur.com/a/60BiMWt_

I tried to edit the file below:
https://github.com/understrap/understrap/blob/master/inc/woocommerce.php#L75

I added this line of code for testing, but nothing happens. 
```
			case 'cookies':
				$args['label_class'] = array( 'custom-control custom-checkbox' );
				$args['input_class'] = array( 'custom-control-input' );
				break;
```

It is strange, because the standard comment form displays correctly on the blog ( thanks to this https://github.com/understrap/understrap/blob/master/inc/custom-comments.php#L47 ), I'm not really sure where woocommerce store the code.

Any idea where to look ? 
Thanks

**Comment by IanDelMar** [comment]
> I'm not really sure where woocommerce store the code.

WooCommerce does not use the cookies field. The field is added in the WordPress function `comment_form()` ([see here](https://core.trac.wordpress.org/browser/tags/5.4/src/wp-includes/comment-template.php#L2273)) which is called by WooCommerce in the template file `single-product-reviews.php` ([see here](https://github.com/woocommerce/woocommerce/blob/b2a0e738669ce9a9eb299180a02902a4322664b1/templates/single-product-reviews.php#L136)).

> It is strange, because the standard comment form displays correctly on the blog

That is the case because the 'standard comment form' does not use any arguments https://github.com/understrap/understrap/blob/44cc2383bdcefafe0f39e559c1c63bfcf7c27cec/comments.php#L119 and thus uses the filtered default values. In `single-product-reviews.php` the comments are displayed via  `comment_form( apply_filters( 'woocommerce_product_review_comment_form_args', $comment_form ) );` where `$comment_form['fields']['cookies']` is not set. What happens in  `comment_form( apply_filters( 'woocommerce_product_review_comment_form_args', $comment_form ) );` is that WordPress first checks whether `$comment_form['fields']['cookies']` is set and if not populates it with the unfiltered default value ([see here](https://core.trac.wordpress.org/browser/tags/5.4/src/wp-includes/comment-template.php#L2361)). When the provided arguments (`$comment_form`) and the default arguments (`$defaults`) are merged ([see here](https://core.trac.wordpress.org/browser/tags/5.4/src/wp-includes/comment-template.php#L2451)), WordPress finds a value for `$comment_form['fields']['cookies']` and does not use the default value. 

So it is neccessary to filter the form field after the arrays of arguments have been merged. The `comment_form_field_{$name}` hook can be used to achieve this ([see here](https://core.trac.wordpress.org/browser/tags/5.4/src/wp-includes/comment-template.php#L2601)) like so 
```php
add_filter( 'comment_form_field_cookies', 'themeslug_product_review_comment_form_field_cookies' );
function themeslug_product_review_comment_form_field_cookies( $field ) {
	if ( is_product() ) {
		$replace = array(
			'<p class="' => '<div class="form-group form-check ',
			'<input'     => '<input class="form-check-input" ',
			'<label'     => '<label class="form-check-label" ',
			'</p>'       => '</div>',
		);
		$field = strtr( $field, $replace );
	}
	return $field;
}
```

For the other form fields you can use
```php
add_filter( 'woocommerce_product_review_comment_form_args', 'themeslug_product_review_comment_form_args' );
function themeslug_product_review_comment_form_args( $args ) {
	$replace = array(
		'<p class="' => '<div class="form-group ',
		'<input'     => '<input class="form-control" ',
		'</p>'       => '</div>',
	);

	if ( isset( $args['fields']['author'] ) ) {
		$args['fields']['author'] = strtr( $args['fields']['author'], $replace );
	}
	if ( isset( $args['fields']['email'] ) ) {
		$args['fields']['email'] = strtr( $args['fields']['email'], $replace );
	}
	if ( isset( $args['fields']['url'] ) ) {
		$args['fields']['url'] = strtr( $args['fields']['url'], $replace );
	}

	$replace = array(
		'<p class="' => '<div class="form-group ',
		'<textarea'  => '<textarea class="form-control" ',
		'</p>'       => '</div>',
	);

	if ( isset( $args['comment_field'] ) ) {
		$args['comment_field'] = strtr( $args['comment_field'], $replace );
	}

	return $args;
}
```

**Comment by carlo-13** [comment]
Hi @IanDelMar thanks again for your help, and very complete answer!

**Comment by IanDelMar** [comment]
If that worked for you, please close the issue.
