### ISSUE TITLE
theme.min.css does not compile

### ISSUE THREAD

**Issue by sayayinR** [understrap/understrap#1220]
Please delete anything that does not apply for you!

## Issue is about..
  - [ x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.1
  - **OS Version:**  Windows 10
  - **Browser:**  all 
  - **Language:** PHP
  - **Node.js & NPM Versions:** 10.15 and 6.9

---

# Issue Overview for Bugreports

Hi, 
I have been stuck on this issue all day. I have gulp watch running in the theme folder but I don't see theme.min.css being loaded in the website. I see the theme.css being compiled in the css folder but it just does not get added to wordpress site. I only see styles.css being loaded. Not sure what am I doing wrong here. I used understrap a while back and that website still runs fine in my local env but not sure why is it not working now. I did the classic install, downloaded the zip from Github. Not sure if some settings or files have changed, I've re-read all the instructions too. 
Can you please guide me in the right direction?
When I compare the newly downloaded gulpfile.js with the old one I downloaded from here over a year ago, I see quite a bit of differences.

**Comment by axlright** [comment]
I'm not gonna offer much help here, but I haven't used `gulp watch` in a while because it can be a lot of trouble, especially with https local sites. Can you run regular `gulp scripts` and `gulp styles` locally to get the js and css to compile?

**Comment by sayayinR** [comment]
@axlright Thanks for your reply. I ran gulp scripts and gulp styles and still the same result. The scripts and styles are being compiled (I can see in the theme CSS folder) but they just don't get added to the website. I was looking at the enqueue.php and I have not changed anything there.  Only two CSS files I see in the code are styles.css for ContactForm plugin and style.css for the theme.

**Comment by axlright** [comment]
Oh then you have something more that's broken. This has to do with how you're enqueuing your styles. You shouldn't be seeing the theme's `style.css` file at all. It's not used for front-end styling. It's only used because WordPress requires it and to note the theme version number.

There could be any number of reasons for this. You can send through the top of your `functions.php` to show how you're enqueuing styles. But this could be a plugin conflict or any number of things also. I'd recommend doing the standard WordPress best practice debugging and try removing plugins, activating default themes, etc until you stumble on the thing that's causing the trouble.

**Comment by sayayinR** [comment]
@axlright Thanks for the input. I fired up a new site with the default theme and I see it is working fine. I can see the theme.min.css being added and style.css is not there just like you said. So guess there is nothing wrong with understap, it is something at my end. I will close this issue. Again thanks for your help.
