### ISSUE TITLE
Has anyone successfully used understrap?

### ISSUE THREAD

**Issue by Chinomso1995** [understrap/understrap#1228]
I was looking to get into WordPress theme development and a friend recommended understrap but it has been a pain to setup. I initially downloaded all files and tried to use the gulp watch command but it gets stuck at starting and does not watch for any changes in the SASS files. I downgraded the gulp file to version 3.9.1 but it threw a primordial JS error which was from my version of Nodejs. I downgraded my Nodejs and I get an error saying gulp.series is not a function. I did my research and it appears gulp, series is only available for gulp version 4,0 and above. Has anyone gotten this to work? I tried looking online and it appears a ton of people have the same issues with no solutions.

**Comment by axlright** [comment]
I've built several dozen websites with Understrap over the years and develop with it every day. Definitely works. The repo isn't actively maintained, though. It was bought (didn't even know that was possible) by a non-developer who has shunned many / all of the community developers. Shame.

**Comment by 0dp** [comment]
@UnderstrapFramework would you care to comment?

**Comment by pattonwebz** [comment]
Many people probably swap in their own build system for this theme. Lots of people have successfully used it though. There is (or used to be) an issue here where people could share links/demos of their works and there is a pretty long testimonials page on the website: https://understrap.com/testimonials/

**Comment by UnderstrapFramework** [comment]
I have used the UnderStrap framework for years and its a great way to start a WP project where you want it to be Bootstrap based.

I prefer my starter themes to be as lightweight as possible so I can "add" rather than "take away" and UnderStrap follows this perfectly.

If you aren't looking for a bare-bones Bootstrap WordPress starter theme then this probably isn't the one for you!

**Comment by axlright** [comment]
@UnderstrapFramework why have you stopped developing the repo and why have you shunned the community of developers who built it?

**Comment by pattonwebz** [comment]
FWIW I do not feel shunnen or pushed away from any contribution I might want to offer here. Open Source projects come and go and repo owners time to manage also comes and goes. If community wants to fork and take the project a different direction that can happen.

Also I don't think this issue thread is the place to have conversations like this since probably OP didn't open this issue to have a discussion about the project management - they had a question about who successfully used it as well as some problems the need to solve so they too can use it.

**Comment by IanDelMar** [comment]
@Chinomso1995 I have successfully used UnderStrap without issues. 
You do need Gulp 4 and you do need node 10|11|12|13 as stated in the package.json.
https://github.com/understrap/understrap/blob/9358ee459f9a8bfe855c3a707d571ece14421f68/package.json#L10
https://github.com/understrap/understrap/blob/9358ee459f9a8bfe855c3a707d571ece14421f68/package.json#L38 

What you wanted to let us know is that gulp watch is not working, right? If you'd be more precise (eg about your setup, which node version, which OS et cetera) someone could at least try to help. That's why you were asked to provide this information when opening the issue...

**Comment by Chinomso1995** [comment]
Hello Guys. I finally got it to work. I had node version 12 installed and it didn't work with gulp watch. So I deleted node and installed the latest version and it worked perfectly. I battled with this for around 3 days. If anyone is having the same issues they can try that.

**Comment by adkhan11** [comment]
Bro u have to enqeue _theme.scss .. and second thing gulp watch will not
work if u haven't install it first I need to install gulp in your project
open terminal and install gulp first ... 3rd thing gulp only works and
starts if u r currently working with css  and saving file with ctrl+s
