### ISSUE TITLE
Can't install via npm

### ISSUE THREAD

**Issue by yushanwebdev** [understrap/understrap#1230]
## Issue is about..
  - a Bug Report

## My environment:

  - **WordPress Version:**  5.4.2
  - **OS Version:** Windows 10
  - **Node.js & NPM Versions:** Node.js [14.15.0] | NPM [6.14.8]
  - **understrap Version** 0.9.3

## Description
I'm using **understrap** as a dependency in wordpress project. I installed gulp and bower globally.
When I run `npm install understrap` got an error like this.

![image](https://user-images.githubusercontent.com/25406148/98235372-b6a14380-1f87-11eb-81db-23ebbbf46efe.png)

## Note
I tried solutions mentioned in https://github.com/understrap/understrap/issues/978 also. But didn't fix.

**Comment by felix-berlin** [comment]
@yushanwebdev this will probably be due to your node version. Under Node v.12 there is no fs.js anymore. I recommend to you to use a Node Version Manager like [NVM](https://github.com/nvm-sh/nvm) and install Node 10. Then it should work.

**Comment by yushanwebdev** [comment]
@felix-berlin as I mentioned in issue my Nodejs version is v12.19.0.

![image](https://user-images.githubusercontent.com/25406148/98230716-78a12100-1f81-11eb-98ff-940836033da5.png)

**Comment by felix-berlin** [comment]
@felix-berlin seen it to late. I answerd you in the issue.

**Comment by IanDelMar** [comment]
Which version of UnderStrap are you using? In the first screenshot it says 0.9.1, in the second it's 0.9.4. The npm version is at 0.9.3.

**Comment by yushanwebdev** [comment]
@IanDelMar I update the screenshot in my inital post also. Understap version is 0.9.3

**Comment by yushanwebdev** [comment]
I update the node version to the latest. But didn't help

![image](https://user-images.githubusercontent.com/25406148/98237650-367cdd00-1f8b-11eb-8379-d5805c1e056f.png)

**Comment by yushanwebdev** [comment]
This saves the day 
https://github.com/understrap/understrap-child/issues/229#issuecomment-551164507

Thanks @felix-berlin & @IanDelMar for the support

**Comment by IanDelMar** [comment]
The `copy-assets` task which is executed as post-install script (see [here](https://github.com/understrap/understrap/blob/577eea7f47aeef222062b3bcea70718058acab87/package.json#L7)) can't find `skip-link-focus-fix.js` which should be located at `./node_modules/undescores-for-npm/js` https://github.com/understrap/understrap/blob/577eea7f47aeef222062b3bcea70718058acab87/gulpfile.js#L221 since `${paths.node}` is defined as `./node_modules/` in gulpconfig.js
https://github.com/understrap/understrap/blob/577eea7f47aeef222062b3bcea70718058acab87/gulpconfig.json#L13
I guess the `./node_modules/` part is the problem. It is relative to the `gulpfile.js` and thus points to `...themes/lymited-child/node_modules/understrap/node_modules/undescores-for-npm/js` which does not exist.
I never tried to install UnderStrap as a dependency and have no ad hoc idea how to solve that issue. However, I strongly recommend to either use v0.9.4 or the master branch as v0.9.3 is outdated.

**Comment by IanDelMar** [comment]
> This saves the day
> [understrap/understrap-child#229 (comment)](https://github.com/understrap/understrap-child/issues/229#issuecomment-551164507)
> 
> Thanks @felix-berlin & @IanDelMar for the support

Ah, you've already found a solution.

**Comment by yushanwebdev** [comment]
yeah @IanDelMar. The reason for the issue is importing the understrap again in child's theme _package.json_.
