### ISSUE TITLE
New version for 2021 with gutenberg support?

### ISSUE THREAD

**Issue by LukaszJaro** [understrap/understrap#1241]
Is there anything in the works that's coming soon? Looks like last update was from June 2019.

**Comment by weartstudio** [comment]
Any news for Bootstrap 5?

**Comment by LukaszJaro** [comment]
No BS5 support https://github.com/understrap/understrap/issues/1211

Until IE11 is decommissioned most likely.

**Comment by LukaszJaro** [comment]
@holger1411 your site has many internal server errors(500) as well https://understrap.com/understrap/

Everything is pointing to this starter theme being abandoned or very low to no maintenance anymore.

**Comment by IanDelMar** [comment]
@LukaszJaro The repo and the site is owned by a guy called (@UnderstrapFramework) since more than a year now (see #1071 and #1073). @UnderstrapFramework is focused on the commercial version of UnderStrap and hardly finds the time to maintain this repo. I highly doubt there will be Gutenberg or BS5 support in 2021.

**Comment by LukaszJaro** [comment]
Omg what a story, wow thanks @IanDelMar for the update!!! What a turbulent transition and insult to the long time contributors... @holger1411 and @UnderstrapFramework handled this transition as bad as they could!

This leaves a bad taste, I started using understrap over a year ago, though it had the right amount of useful features, not over-engineered, helpful build tools, basically a realistic framework where you can get real work done with. Also I thought can't go wrong with German built theme!(In Canada anything German built is regarded as very high quality)

I'm still processing this, but so far doesn't sound to good.

**Comment by weartstudio** [comment]
I understand that the development management is a frustrating thing, especially the free one. BUT. I think you can’t sell your commercial product without a strong updated and well maintained base framework. If the people are satisfied with the base theme you can upsell them more products. IF they satisfied. But now the I am only a frustrated developer who can’t decide   to use this fw instead the genesis (which i use now).

**Comment by LukeVibes** [comment]
I actually bought the paid version bundle- none of it worked. Child theme failed to correctly npm install and was offered zero help. They gave me a full refund and said sometimes it doesn't work.

**Comment by LukaszJaro** [comment]
@LukeVibes ouch, harsh. Even the commercial side is neglected.

@IanDelMar thanks for all the updates, I noticed you're making commits to the master(updating bootstrap, etc), is it stable enough to use?

**Comment by KyleDearle** [comment]
@LukeVibes Thank you for sharing this info. I had started to consider buying the commercial version since having problems with the repo. Very frustrating, this is/was a great framework.

**Comment by bacoords** [comment]
Two big notes here: 

The next major release will be focusing on BS5 integration. (First we just want to make sure the theme repository gets all of the commits that are done on master since the 0.9.4 release). 

Similarly, we'll need to review what is missing in terms of gutenberg and focus on that immediately afterwards (I'm guessing full width blocks, some backend styling, color palettes, etc).

**Comment by pattonwebz** [comment]
Feel free to ping me on WordPress slack (username there is `williampatton`) and I can help get this through to live on the .org repo (since it's been over 2 years since it was updated there it won't go live when updated - it will go to a review queue and need approval from someone on the theme-review team).

**Comment by bacoords** [comment]
Hi all, 

A few notes and I'm going to close this issue. 

We're starting to track gutenberg-specific issues separately and have added them to the roadmap. This issue doesn't mention specific changes needed to support gutenberg, so I'm going to close it and ask anyone who has a specific gutenberg-related request to start a new issue so we can triage it.

Also, the [starter child theme](https://github.com/understrap/understrap-child) has been updated and the npm issues cleared up. We recommend using it if you're doing custom theme development. We (the owners) are also going through the paid child themes separately and checking for bugs. 

And finally, the main branch of this repo now matches the "official" version in the repository, which is now being continually updated, thanks to all who contributed.
