### ISSUE TITLE
OverStrap: Masonry not fitting inside content container with WordPress theme unit test data

### ISSUE THREAD

**Issue by SRD75** [understrap/understrap#1243]
## Issue is about..
  - [*] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 5.6
  - **OS Version:** Windows 10
  - **Browser:** Chrome
---

# Issue Overview for Bugreports

## Steps to reproduce?

1. Activate OverStrap: Masonry
2. Import WordPress theme test unit data

## *Who* is the bug affecting?

Website visitors

## *What* is affected by this bug?

The website

## *When* does this occur?

Every page load

## Screenshots / Video

[screenshot](https://steve.doig.photography/files/2021/01/screencapture-themedevelopment-local-2021-01-18-18_46_57.png)

## Expected behavior

Masonry layout fits inside of a container same width as the header.

**Comment by IanDelMar** [comment]
Hi @SRD75 , this is the repo for UnderStrap. While UnderStrap is a free theme, OverStrap is a collection of commercial UnderStrap child themes sold by @UnderstrapFramework who took over UnderStrap about a year ago. IMHO, this repo isn't the right place to look for OverStrap support, report OverStrap bugs, .... I suggest to follow the instructions on https://understrap.com/overstrap/:
>I'm stuck and can't get something to work, can you help?
Of course! Open a support ticket through the WP Extend website or catch us on live chat on that site or this one. We will gladly help with any OverStrap issue.

Good luck!

As your issue is not related to UnderStrap but OverStrap: Masonry may I ask you to close the issue? Thank you!

**Comment by SRD75** [comment]
Nice one, thanks @IanDelMar
