### ISSUE TITLE
Enqueue basic bootstrap styles into the block editor for font, colors, etc.

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#1296]
Obviously we don't want ALL of bootstrap loaded in the back end- but loading your fonts, colors, etc is really helpful in terms of getting the backend to match the front. This is a preliminary method to add new elements to the `custom-editor-styles.scss` file. It loads our variables and some core Bootstrap stuff, then after that we can see if we need anything else added as well.

```scss
@import "theme/_theme_variables";
@import "../src/sass/bootstrap4/functions";
@import "../src/sass/bootstrap4/variables";
@import "../src/sass/bootstrap4/mixins";
@import "../src/sass/bootstrap4/root";
@import "../src/sass/bootstrap4/type";
```

We'll also need to explicitly declare that we want this file loaded in the block editor, not just tinyMCE in `/inc/setup.php`
```php
add_theme_support( 'editor-styles' );
```

**Comment by danemorgan** [comment]
Do we need to support two editor-style sheets? One for the MCE and one for the block editor, or will a single stylesheet work for both.

I was reading something the other day that suggested it might need both because with MCE you are targeting the MCE iframe, but with the block editor, it adds its own targeting assistance because there is not iframe, and it needs to target a portion of the page. That seemed to suggest each might need its own stylesheet?

**Comment by bacoords** [comment]
No you use the same stylesheet, since it's actually the same enqueue function. But you have to use `add_theme_support( 'editor-styles' )` to explicitly say you want it loaded in the block editor as well, because there are a few distinctions you have to account for:

https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#editor-styles

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
