### ISSUE TITLE
Can't enter anything in the input fields at checkout

### ISSUE THREAD

**Issue by Havbaba** [understrap/understrap#1302]
## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.7.2
  - **OS Version:** Windows 10
  - **Browser:** Chrome 91.0.4472.114 | Firefox 89.0.1 (64-bits)

# Issue Overview for Bugreports

## Steps to reproduce?
Go to my website (I made a staging/test copy of my live site) [https://staging-dronedepot.kinsta.cloud/](url)
Add something to your basket and press the cart button on the top-right and press checkout.
At the checkout page you can't enter anything in the input fields...

## *Who* is the bug affecting?
Everyone

## *What* is affected by this bug?
Input fields on checkout page

## *When* does this occur?
Always

## Screenshots / Video
[https://pasteboard.co/K8phcuR.jpg](url)

### Other Comments
I disabled all other plugins and changed theme, and I am sure it's the problem start from understrap version 0.9.5 and 0.9.6.
Problem disappears when rolling back to 0.9.4

**Comment by howarddc** [comment]
Thanks, we'll take a look right away.

**Comment by danemorgan** [comment]
Hi @Havbaba,

Thanks for using Understrap Framework.

A [stylesheet](https://staging-dronedepot.kinsta.cloud/wp-content/plugins/woofunnels-aero-checkout/assets/css/wfacp-form.min.css?ver=2.7.2) loaded by a plugin called  Woo Funnels AeroCheckout is setting your labels over the top of the input fields. The text is being entered, but because the labels are positioned over the top of the input, you cannot see it.

Here is the selector affecting this.
```
#wfacp-e-form label.wfacp-form-control-label {
    position: absolute;
    top: 50%;
    left: 19px;
    margin-top: -10px;
    transform-origin: left top;
    color: #969595;
    font-size: 15px;
    line-height: 20px;
    font-weight: 400;
    background-color: #fff;
    pointer-events: none;
    transition: all .235s ease;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    z-index: 9;
    bottom: 5px;
    right: 20px;
    margin-bottom: 0;
}

I was able to achieve the results in the image below by setting 'top: 12px' and `bottom: initial` in the dev tools inspector. You may need to use the !important keyword in your child theme's styles for these rules to override the plugin's style rules.

![image](https://user-images.githubusercontent.com/1909081/123518221-8fa89680-d66a-11eb-820b-b2df99d6b117.png)

```

**Comment by Havbaba** [comment]
That works indeed!
Big thanks @danemorgan <3

But the problems start with the Understrap update, so Understrap need to adapt their code and not Woofunnels, right?
Or am I wrong?

**Comment by pattonwebz** [comment]
Seems like a conflict between Woofunnels and Bootstrap and likely neither side is actually causing the problem - they are just incompatible. A small piece of integration CSS seems acceptable to me that it could be added to a child theme - or even via the customizer CSS input - as the fix.

**Comment by danemorgan** [comment]
Hi @Havbaba 

Adding to what @pattonwebz said so well, I will note that my personal opinion is that design choices like these are properly the domain of themes. Themes, when doing_it_the_WordPress_way() are for styling the site and are forbidden to enter plugin territory.

Likewise, I feel that plugins need to avoid opinionated styling and stay out of theme territory. That said, it's a more delicate balance, because plugins do need to provide some sane fallback styling just in case, but I am a believer that they should do so in an unopinionated way so far as possible and provide explicit ways for users to override the plugin style in favor of the theme style.

Setting a form label to absolute positioning and providing it a top and a bottom setting is pretty opinionated. Without digging into things, I'm guessing that there was some padding to margin in the Bootstrap input container that was removed at some point in the past two years. Which is a valid design choice for Bootstrap to make. In reality, Bootstrap likely made such a choice in response to some number of users having problems with other components conflicting with the spacing that made your labels work well previously. Any CSS change has this same potential to simultaneously break and fix different sites.

This is why Understrap and WordPress make it as easy as possible for end-users to add their own CSS to fix these conflicts and why I'm happy to dig into CSS issues for other people any time. 😁😎

I'm going to go ahead and close this as resolved. if you need anything more, let us know, and again, thank you for using undersatrap.

**Comment by Havbaba** [comment]
It's alright, I was just wondering and trying to understand the cooperation between the 2 :)
I'm very glad you helped me and are willing to help other with CSS problems! :D

Cheers 🍻

**Comment by Havbaba** [comment]
I contacted Woofunnels and they sent me an updated version of their plugin.
This update will be published later on.

[woofunnels-aero-checkout-v2.8.1.beta-f-3208.zip](https://github.com/understrap/understrap/files/6735939/woofunnels-aero-checkout-v2.8.1.beta-f-3208.zip)
