### ISSUE TITLE
Too many landmark roles in sidebar

### ISSUE THREAD

**Issue by IanDelMar** [understrap/understrap#1349]
### Bug Description
There seem to be excessive landmark roles in the sidebar. The sidebar itself has a landmark role of complementary, each widget has a a landmark role of complementary because they are all wrapped in `<aside>` which has complementary as native role. On top there is the search form having it's search role.

### Steps to reproduce
Steps to reproduce the behavior: Check the corresponding template files.

It's
- complementary (div coming from sidebar-right.php)
  - complementary (aside coming from widgets.php)
       - search (form coming from searchform.php)
  - complementary (aside coming from widgets.php)
  - complementary (aside coming from widgets.php)
  - complementary (aside coming from widgets.php)

### Expected behavior
Less landmark roles.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/42134098/127644144-de942fc7-9e0e-4b33-a5e1-5ac91ec25332.png)

### The Environment
Does not depend on the environment.

### Additional context
I'm not an expert on accessibility. But I think either the whole sidebar is the complementary content and the widgets are like sections (i.e. need to be unwrapped from the asides) or the sidebar does not have a role but the widgets have the role complementary via the aside element. The search form should not be wrapped in an aside I think. Maybe someone who knows more about accessibility than me can share their opinion on that. What about you @Thomas-A-Reinert ?

**Comment by Thomas-A-Reinert** [comment]
Hey @IanDelMar - I assume https://demos.understrap.com/ is running on the latest version. Got no own installation running the latest version.

Well, asides in asides are allowed syntactically, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside even if that makes no sense at all to me from a semantic perspective.

My recommendation would be the following:

1. The sidebar itself should become a section with no landmark at all. And it should have an sr-only headline for visually impaired users who can jump between headlines.
2. The widgets should keep their aside tag. In case you see any `role="complementary"` (which I cannot see/find on widgets on the link above) – get rid of it. Because with an aside this role is already implicit. Keeping them won´t hurt though, it´s just overdoing it. Rule of thumb: Keep landmarks as sparse as possible.
4. Well, the search form.. 

- it shouldn´t be wrapped in an aside. The search got a role of it´s own.
- there shouldn´t be no two role="search" on one page. While this is somehow "okayish" from a syntactial perspektive, it´s misleading from a blind users perspective. No clue how to make sure that there are no duplicates and just a single one, because you can have a search in the header, menu, on the search page, in the sidebar. In case that´s not solvable, well.. just keep the roles. Not everything can be 100% elegantly solved when using CMS´s.

![image](https://user-images.githubusercontent.com/5886977/127650305-aab35a13-b7b8-47d2-9d55-b5b1563bd4e5.png)

**Comment by Thomas-A-Reinert** [comment]
Just quick-checked the rest..

- i´m really missing a <header>
- id="wrapper-footer-full" (the "Sample Footer Widget" area) should be a section with a sr-only headline describing the purpose/content of this section.

**Comment by IanDelMar** [comment]
> Well, asides in asides are allowed syntactically, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside even if that makes no sense at all to me from a semantic perspective.

Maybe if the aside has content on its own. But it doesn't in this case.

> The sidebar itself should become a section with no landmark at all. And it should have a (descriptive!) sr-only headline for visually impaired users who can jump between headlines.

What could that headline be? "Right Sidebar"? We don't know what the user will put in there. And will the right sidebar always be the right sidebar - even in an rtl context?

> it shouldn´t be wrapped in an aside. The search got a role of it´s own.

I'll have to think about how we can achieve this

> there shouldn´t be no two role="search" on one page.

I think there is a solution to this. But wouldn't a second search form searching different things, e.g., products require another role search?

Another sidebar related question: I read that the position of the sidebar should not change from page to page.  Wouldn't it be good then to apply the default position of the sidebar to the search.php and 404.php as well?

**Comment by IanDelMar** [comment]
Another question. What's wrong with `aria-label`? Because here (https://www.w3.org/TR/wai-aria-1.1/#aria-labelledby) it says that:

> If the interface is such that it is not possible to have a visible label on the screen, authors **_SHOULD_** use aria-label and **_SHOULD NOT_** use aria-labelledby. As required by the text alternative computation, user agents give precedence to aria-labelledby over aria-label when computing the accessible name property.

**Comment by Thomas-A-Reinert** [comment]
> > Well, asides in asides are allowed syntactically, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside even if that makes no sense at all to me from a semantic perspective.
> 
> Maybe if the aside has content on its own. But it doesn't in this case.

Maybe https://html.spec.whatwg.org/multipage/sections.html#the-aside-element is the better source as it also has some accessibility considerations. But none of both limits the aside´s usage besides "flow content". And it´s  a flow content element itself. So could syntactically still have a thousand nested asides. It won´t make sense, but it´s still "valid".


> > The sidebar itself should become a section with no landmark at all. And it should have a (descriptive!) sr-only headline for visually impaired users who can jump between headlines.
> 
> What could that headline be? "Right Sidebar"? We don't know what the user will put in there. And will the right sidebar always be the right sidebar - even in an rtl context?
 
Good question and you´re already answering it to yourself ;)
"_Right Sidebar_" and "_Left Sidebar_" make just as much sense as "_Click the green button_" when i´m blind/colour-blind . "_Sidebar_" does describe it´s function/intention sufficiently. No matter if it´s right/left and or turned around by rtl.

> > there shouldn´t be no two role="search" on one page.
> 
> I think there is a solution to this. But wouldn't a second search form searching different things, e.g., products require another role search?

Usually users with a little coding experience (and no a11y background) will just copy paste the search either from the widget and/or searchpage. Besides, the stock search searches through almost everything. Be it a post, page, comment, product or whatever.
And yes, I agree. You should add another role search then. But it should have a different heading/aria-label/aria-labelled-by then so that the users knows what this second search is actually doing/searching for. But that´s a different topic and probably out of scope of a "starter theme". 


> Another sidebar related question: I read that the position of the sidebar should not change from page to page. Wouldn't it be good then to apply the default position of the sidebar to the search.php and 404.php as well?

Hm.. Interesting question again. May I ask where you exactly read that? A link would be helpful. I´m just asking because... There´s actually a whole lot of ressources about "accessibility". But honestly, just a handful who you can actually trust. Many people have "opinions" and "solutions" these days. (Just read about "accessibility overlays" that actually gain max attention. But do NOT solve ANY a11y problem at ALL.) But just as many are not really helpful/really solving the problem.
And almost none of them are really affected. That´s like "_I don´t even have a driving license but I´m trying to teach people how to drive_". Because they´re sighted, don´t understand the problem from a non-sighted/colour-blind/screen-reader perspective, etc. etc..

I´d put the content ("main") on top of the DOM, sidebars after that and sort all sidebars by flex-order anyway. Yes, consistency is a thing. Afaik (and sorry, I´m still no EXPERT!) it´s no problem to discard a sidebar on the one or other page. You´re not "changing positions" then, are you? ;)


> > i´m really missing a .
> 
> a header or a heading?


&lt;header>
That "thing on top" would qualify for header. 

> > id="wrapper-footer-full" (the "Sample Footer Widget" area) should be a section with a sr-only headline describing the purpose/content of this section.
> 
> Same problem: a priori we don't know the purpose.
True. That thing could be anywhere. I´m just saying that the implementation on the demo-site actually sucks a lot.

**Comment by Thomas-A-Reinert** [comment]
> Another question. What's wrong with `aria-label`? Because here (https://www.w3.org/TR/wai-aria-1.1/#aria-labelledby) it says that:
> 
> > If the interface is such that it is not possible to have a visible label on the screen, authors **_SHOULD_** use aria-label and **_SHOULD NOT_** use aria-labelledby. As required by the text alternative computation, user agents give precedence to aria-labelledby over aria-label when computing the accessible name property.

Well, nothing wrong with it at all.
aria-labels as well as aria-labelledby just don´t give you any hint about the document outline that can easily be made accessible by using a headings structure. Please install and try https://github.com/dzc34/headingsMap on Chrome/Firefox and play around with a heading and all other options. Just the headline will give you an outline of all sections available that you can actually jump to.
aria-label etc. won´t

**Comment by Thomas-A-Reinert** [comment]
Addon to the last post:

- aria-labels as well as aria-labelledby won´t show for any sighted users anyway.
- sr-only headlines will neither.
- adding a sr-only headline will solve all problems with least effort overall.
  - it ain´t visible.
  - no need to trick around with an (sorry... "for you") uncanny valley with aria-labels etc.
  - but it WILL give structure (and explain purpose) for any non-sighted user or those that disable stylesheets or whatever.
 

In case you want that perfected to the max: Use aria-labelledby for the section and reference the ID of the subordinate headline.
But that´s totally over the top according complexity for coding etc. while my proposal solves that all at once.

**Comment by pattonwebz** [comment]
>Hm.. Interesting question again. May I ask where you exactly read that? A link would be helpful. I´m just asking because... There´s actually a whole lot of ressources about "accessibility".

I would also be interested to get a link for this that I can use for reference in future too. I know from personal experience that keeping consistent sidebar placement aids the processing of pages so I am certain it is a good practice for certain groups of a11y needs. I am in one of those groups :) I am also in the group of color blind folks as well if there are any questions about colors feel free to ping me anytime :)

**Comment by Thomas-A-Reinert** [comment]
I guess you're fully sighted and not colorblind or anything? Is actually anyone in this group? 

Just because I'm curious : What qualifies you for that group?

**Comment by howarddc** [comment]
Hi all, 

I'm open to everyone's ideas on our exact technical solutions here. However, for this and all future accessibility discussions, I want to clarify a few important guidelines:

- Anyone can contribute to the accessibility discussion. There is no requirement to have a visual impairment or disability to constructively contribute here. 
- No one is ever required to disclose any information here or elsewhere about any visual impairment, disability or other medical condition.
- The general goal is to be ADA complaint and Section 508 compliant (these are both US statutes), with the understanding that Understrap is a starting point, and that we don't ultimately control final content on the sites built with Understrap. 
- Please do not use profanity. Adding a * to a word does not change the unprofessional nature of the word. A large community of users has access to this discussion and it is important that we make it a welcoming and positive place for everyone. Using unprofessional language degrades the experience for everyone involved.

**Comment by Thomas-A-Reinert** [comment]
That's why I edited my post.
Thanks for clearing up on Ada and 508. Guess you just kinda forgot about elementary WCAG 2.1, but *hey*
And I see no problem on also fulfilling any standard that's built on top of WCAG 2.1, ADA and 508, do you? There are actually a lot more international standards built on top of those three. Fulfilling those would not hurt US standards.
Did I use profanity? I kinda feel addressed but can't see the poi t.

**Comment by pattonwebz** [comment]
>You don't need to answer that thing here just because I AM interested in it. I guess you know how to contact me personally?

Message sent to you on your personal website :)

**Comment by howarddc** [comment]
@pattonwebz No worries, thank you!

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert @pattonwebz 

> Hm.. Interesting question again. May I ask where you exactly read that? A link would be helpful. I´m just asking because... There´s actually a whole lot of ressources about "accessibility". 

> I would also be interested to get a link for this that I can use for reference in future too.

I had a hard time to reconstruct where I read that but here it is

https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation.html

However, I over-interpreted the phrases "consistent presentation and layout" and "same order". While it's probably more predictable and consistent when a sidebar appears on every page or no page at all, a sidebar not being shown on one page does not violate "consistent layout" or "same order" because the rest of the page is in the same order. It would be a violation if the same sidebar appears right on page and left on another page. 

In this specific case, I wonder whether it would be better to have the default sidebar there and only show the widgets if there is no sidebar. Chances are good that the sidebar contains some of the information the widgets provide and that would in fact violate "consistent layout" and "same order". What do you think?

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
