### ISSUE TITLE
Child theme still "needed"?

### ISSUE THREAD

**Issue by manuelschroederdev** [understrap/understrap#1364]
Hi all,

in the past I've developed using the Understrap Child Theme but switched to Roots Sage last year because I kept running into issues with NPM and Node with the Understrap Child Theme.

I've now checked it out again as I'll need it for a new project and was a bit surprised that it still requires Node 8 and fails to install without issues.

Is it possible/recommended to build directly using the parent theme these days? Because in the official docs, it is still recommended to take the child theme approach.

Would appreciate your support!

**Comment by bacoords** [comment]
You can definitely use the parent theme and modify it as needed. While we recommend the 'official' WordPress method of using a child theme, there's no reason you can't rename the theme and use it. Just make sure it's not 'Understrap' and the directory is not 'understrap' so that WordPress doesn't try to auto-update it and overwrite your code with the theme is updated in the theme repository.

**Comment by bacoords** [comment]
@manuelschroederdev Please let us know if you have more questions or if we can mark this as closed.
