### ISSUE TITLE
Custom inc/template-tags.php not loaded in child theme

### ISSUE THREAD

**Issue by daveaalitz** [understrap/understrap#1413]
### The Bug
After upgrading from 0.9.6 to 1.0.0 viewing single posts caused a critical error and generated this entry in the Apache error log:

`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function understrap_post_nav() in /var/www/wordpress/wp-content/themes/understrap-child/single.php:36\nStack trace:\n#0 /var/www/wordpress/wp-includes/template-loader.php(106): include()\n#1 /var/www/wordpress/wp-blog-header.php(19): require_once('...')\n#2 /var/www/wordpress/index.php(17): require('...')\n#3 {main}\n  thrown in /var/www/wordpress/wp-content/themes/understrap-child/single.php on line 36'`
 
My child theme wasn't loading my custom inc/template-tags.php. When I viewed a single post, single.php couldn't load the understrap_post_nav() function.

Seems similar to #1278 - but at least my custom inc/customizer.php is getting loaded. I haven't verified whether other custom includes are loading.

I added `require_once get_template_directory().'/inc/template-tags.php';` to functions.php to workaround the issue.

### The Environment

- **WordPress Version:** 5.8.1
- **OS Version:**  Linux [Ubuntu / 18.04 (azure)] 
- **Browser:** all
- **Language:** PHP 7.4
- **Node.js & NPM Versions:** Node.js [V10.23.2] | NPM [V6.14.10]

**Comment by bacoords** [comment]
Because we may introduce new functions in any of the `/inc/` directory files, we don't recommend overriding the entire file (though I understand the repo has gone back and forth on allowing this, even in the conversation on https://github.com/understrap/understrap/issues/1278). 

If you're overriding the entire file in your child, you'll need to review each release ahead of time for any new functions that are added and referenced throughout the theme.

We also address this topic in the documentation: https://docs.understrap.com/#/understrap-child/functions

**Comment by daveaalitz** [comment]
Thanks. I must have missed the switch from replacing entire files to just functions. I'll review the `/inc/` directory in my child theme and get it updated.
