### ISSUE TITLE
Modify or override generated editor-color-palette.json

### ISSUE THREAD

**Issue by andymagill** [understrap/understrap#1415]
I am attempting to change the guttenberg editor default color palette and associated CSS in an Understrap child theme.  But I see that these colors are hardcoded from the _understrap palette generator_ dependency here :

[https://github.com/bacoords/postcss-understrap-palette-generator/blob/main/index.js](https://github.com/bacoords/postcss-understrap-palette-generator/blob/main/index.js)

Modifying that dependency is obviously a bad idea for a few reasons.  What would be the correct process to update these colors in the generated JSON and associated CSS classes ?

**Comment by andymagill** [comment]
I can see there has been some [discussion of this here](https://github.com/understrap/understrap/issues/1295#issuecomment-873292284) and a gulpfile from another branch that also has the hardcoded values. Not sure how to incorporate that file into my child theme.

**Comment by bacoords** [comment]
Great question and something we should add more clarification to in the docs. 

The values come from the json file [here in your child theme](https://github.com/understrap/understrap-child/blob/main/inc/editor-color-palette.json) - the JSON file is auto-generated by our new build process, so if you change any bootstrap color variables, the colors will be updated in that JSON file. The dependency you referenced is just a postCSS plugin (though I agree we might add more options to it in the future so that it's more 'configured' in the theme itself). 

If you're using an older child theme with the older build process, you can either 

1. manually create the `/inc/editor-color-palette.json` file yourself 
2. hook into the `understrap_theme_editor_color_palette` filter to override it with your own palette
3. override the entire  `understrap_block_editor_setup()` function and handle your own Gutenberg-specific setup.

**Comment by andymagill** [comment]
I'm using 1.0.0 of understrap, with a fresh version of the child theme. 

Did an earlier version of the project contain the hardcoded color keys in a gulpfile?  That seems like an improvement over the current setup where only existing keys of the $colors map will be updated in the JSON, and new key/values ignored.

For now, I've decided to update the $colors map in _/src/assets/boostrap4/variables.scss_ of my child theme, and create a new custom JSON file, and override _/inc/block-editor.php_ to load my custom JSON file.

I realize this adds some brittleness to my child theme, but I don't see a better workaround.

**Comment by bacoords** [comment]
Sort of - we originally added this feature before we migrated the theme from gulp, so the original version was in the `gulpfile.js`. BUT we migrated away from gulp before we ever released that update. It was always on our `develop` branch. So we had to write a separate postCSS plugin instead. 

Here's what I think we might do:

Move the original set of colors from being coded [here](https://github.com/bacoords/postcss-understrap-palette-generator/blob/main/index.js) as `const colors` to being passed as an option in [src/build/postcss.config.js](https://github.com/understrap/understrap/blob/main/src/build/postcss.config.js). Then similar to how you were able to modify it in the `gulpfile.js`, you could update the variables in the `postcss.config.js` file. How does that sound?

**Comment by andymagill** [comment]
That sounds more like the solution I had in mind, IF postCSS can also generate the SCSS variables to be processed with the rest of the CSS.  Otherwise, I don't really care if I'm updating a SCSS file or a build config because I still need to maintain those color values elsewhere. 

I kinda think the reverse might be a good alternative, where PostCSS consumes a JSON and renders the SCSS. That could potentially provide a single file to update editor palette, editor css and front css.

**Comment by bacoords** [comment]
@andymagill 

I've updated the postcss plugin so that you can modify what color names/variables you want. For example, you could set it up to also grab your --primary, --secondary, etc values. You'll probably just need to write the CSS for gutenberg as well, if you haven't already. I added two new options you can pass as parameters and broke it all down in the [readme](https://github.com/bacoords/postcss-understrap-palette-generator) file. You'll just need to update it via NPM in your project to use the new options.

Let me know if this closes the issue for you, or if you see anything missing here!

**Comment by andymagill** [comment]
Fantastic! This solution works nicely and more than I ever expected. Thanks again for the great work !
