### ISSUE TITLE
Release 1.0.1 broke our dropdown menu

### ISSUE THREAD

**Issue by Broekhuis** [understrap/understrap#1510]
Hi,

The 1.0.1 release broke our dropdown menu. A javascript error learned that popper.min.js was missing, so we inserted it. After that there were no more js errors, however the menu-dropdown still didn't work..

We installed a backup with a previous version of understrap, which solved the issue.

Any idea?

Regards,

Erik

**Comment by 0dp** [comment]
@bacoords was this not fixed in last patch?

**Comment by bacoords** [comment]
@Broekhuis Are you using a child theme? If so, what version does it show in the package.json file?

**Comment by Broekhuis** [comment]
@bacoords "version": "0.5.3" However, the problem was solved by installing a backup of the main theme (not the child)..

**Comment by bacoords** [comment]
👍The child theme should be loading it's own JS files instead of pulling them from the theme. However, in older versions the parent theme did provide popper.js separately as a dependency, I believe. I'mt thinking that you can keep Understrap parent where it's at instead of updating in the future. OR you can modify your child theme to load popper.js.

**Comment by bacoords** [comment]
Closing this comment due to time. If it's still ongoing, please comment and we'll re-open.
