### ISSUE TITLE
Hamburger Hardships

### ISSUE THREAD

**Issue by televators** [understrap/understrap#342]
(Using latest version of Understrap.)

I'm working on styling the hamburger icon but no matter what I do, I can't change the actual bars SVG. I can't change it's size, weight, color, anything. I can style it's background and container, but not the actual SVG bars themselves.

How am I supposed to style it? The bars are so light and thin that they're hard to see. The site I'm working on has an older audience where eye troubles will be pretty common so I need to make the bars bolder and darker or something. Ideas?

**Comment by willgorham** [comment]
Do you mean the navbar hamburger? As far as I can see there's no SVG icon there at all...

This is the HTML:
```
<button class="navbar-toggle hidden-sm-up" type="button" data-toggle="collapse" data-target=".exCollapsingNavbar">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
```

The bars are styled with a 1px border. So to make them thicker you could do something like:
```
.navbar-toggle .icon-bar {
  border-width: 3px;
}
```

Does that help? Let me know if this isn't what you're talking about.

**Comment by davechu** [comment]
Televators, 
I took a quick look at the demo, which does indeed seem to use an SVG for the hamburger background. I can't give you a solid fix, but will try to point you in a direction.

In theme.css, there are 3 instances of .navbar-toggler-icon. They look like variations of that are paired with other classes. Each has code for a background image using SVG code. You could try commenting those lines out, and then just doing a background-color of #fff for plain old white.

Or you could try editing. When the color is defined as (255, 255, 255, 0.5), you have straight white, but only with 50% opacity, giving color with much less whiteness. "1" would be completely opaque. I'm on shakier ground here, because I don't deal with SVG's in my regular work. 

Hope that helps,
Dave

PS: this theme really looks interesting!

**Comment by tellstevens** [comment]
Televators,

I had to do deal with this yesterday and this got me in the right direction. [https://www.codeply.com/go/4FdZGlPMNV/bootstrap-4-custom-navbar-toggler-icon-color](url) Look at how he did his pink hamburger. You can just open up photoshop and get the rgb values for the color you want.

**Comment by axlright** [comment]
Closing this issue as it is related to Bootstrap itself and not UnderStrap. These Bootstrap variables can be used to control the color of the hamburger:

```
$navbar-dark-color:                 rgba($white, .5) !default;
$navbar-dark-hover-color:           rgba($white, .75) !default;
$navbar-dark-active-color:          $white !default;
$navbar-dark-disabled-color:        rgba($white, .25) !default;
$navbar-dark-toggler-icon-bg:       str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='#{$navbar-dark-color}' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E"), "#", "%23") !default;
$navbar-dark-toggler-border-color:  rgba($white, .1) !default;

$navbar-light-color:                rgba($black, .5) !default;
$navbar-light-hover-color:          rgba($black, .7) !default;
$navbar-light-active-color:         rgba($black, .9) !default;
$navbar-light-disabled-color:       rgba($black, .3) !default;
$navbar-light-toggler-icon-bg:      str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='#{$navbar-light-color}' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E"), "#", "%23") !default;
$navbar-light-toggler-border-color: rgba($black, .1) !default;
```
