### ISSUE TITLE
npm install understrap is empty

### ISSUE THREAD

**Issue by dylannirvana** [understrap/understrap#350]
It doesn't seem like npm install understrap is working. Getting a ENOENT.

**Comment by Retroclasica** [comment]
I find the same problem. I get ENOENT and node_modules but nothing else.

**Comment by dylannirvana** [comment]
It is leaving a lockfile of the package-lock.json. I am wondering why it did this, and how to unlock it, if that is indeed what one should do at this point, because obviously the install wants a package.json. Odd. Thoughts?

**Comment by 0dp** [comment]
@dylannirvana @Retroclasica I've just tested `npm install understrap` and it installed UnderStrap correctly. does this problem still persist? If so, could you please fill this form out:

```
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - WordPress Version: 4.9.x
  - OS Version: [Windows 7 | Windows 8 | Windows 10 | Linux [Distribution / Version] | MacOsX [Version | Android[Version] | iOS[Version]
  - Browser: [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - Language: [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - Node.js & NPM Versions: Node.js [V X.XX] | NPM [V X.XX]


---

# Issue Overview for Bugreports

## Steps to reproduce?

## *Who* is the bug affecting?

## *What* is affected by this bug?

## *When* does this occur?

## *Where* on the platform does it happen?

## *How* do we replicate the issue?

## Are there any related Issues and/or PRs?

## Screenshots / Video

## Expected behavior

# Todos

 * Test
 * Documentation



### Other Comments
```

**Comment by Thomas-A-Reinert** [comment]
MUST work by now. Closing this issue.

**Comment by frontenddevguy** [comment]
This is still the case for me. Just tried npm install understrap and I just get a created package.json and modules folder.

`npm WARN saveError ENOENT: no such file or directory, open '/Applications/AMPPS/www/scorestrap.test/wp-content/themes/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.`

Is it requiring Gulp4?

**Comment by 0dp** [comment]
It's not requiring gulp4 just yet.

It looks like you are trying to run npm install from the themes folder. That won't work :)
You need CD into the theme folder first

**Comment by frontenddevguy** [comment]
Exactly the same thing happens if I create a folder called understrap and then npm install understrap

`/A/A/w/s/w/t/understrap ❯❯❯ npm install understrap
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> fsevents@1.2.7 install /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> node-sass@4.11.0 install /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/Yan/.npm/node-sass/4.11.0/darwin-x64-67_binding.node

> node-sass@4.11.0 postinstall /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/node-sass
> node scripts/build.js

Binary found at /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/node-sass/vendor/darwin-x64-67/binding.node
Testing binary
Binary is fine

> gifsicle@4.0.1 postinstall /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@4.0.0 postinstall /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@5.1.0 postinstall /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> understrap@0.9.1 postinstall /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/understrap
> gulp copy-assets

[11:38:54] Using gulpfile /Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/node_modules/understrap/gulpfile.js
[11:38:54] Starting 'copy-assets'...
[11:38:54] Finished 'copy-assets' after 9.11 ms
npm WARN saveError ENOENT: no such file or directory, open '/Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Applications/AMPPS/www/scorestrap.test/wp-content/themes/understrap/package.json'
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN gulp-imagemin@5.0.3 requires a peer of gulp@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN understrap No description
npm WARN understrap No repository field.
npm WARN understrap No README data
npm WARN understrap No license field.

+ understrap@0.9.1
added 996 packages from 596 contributors and audited 10366 packages in 38.312s
found 8 vulnerabilities (3 low, 1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details`
