### ISSUE TITLE
What gulp script to run on deployment.

### ISSUE THREAD

**Issue by tim-field** [understrap/understrap#378]
I've been asked to deploy a project built with this theme to a production server, for which I'll use [shipitjs](https://github.com/shipitjs/shipit).

What gulp command do I run to do a production build? I'm looking for a gulp build script and I can't see one.

**Comment by holger1411** [comment]
Hey, sorry for my late reply.
`gulp dist`
is the right command to create a distribution folder with anything you need on your live site but without the dev stuff.
You just need to upload the content of the /dist folder to your live systems /wp-content/themes/understrap folder via your deploy script

**Comment by axlright** [comment]
Closing as @holger1411 provided useful feedback.

**Comment by currentcreative** [comment]
why is understrap within the node_modules directory to begin with? When I go to export the site, WP says it can't find 'node_modules/understrap' because I used `gulp dist` and then uploaded that folder to the live server. I figured maybe I would have to rename it 'understrap' but I don't want to be putting it in a folder called 'node_modules' for no reason. This is how a standard installation of `npm install understrap` organized the files for some reason instead of putting node_modules in a separate folder. 

Is there a way to install Understrap differently that will still run Gulp and BrowserSync properly?

**Comment by currentcreative** [comment]
Ok, well I tried a different installation approach by downloading the zipped theme, activating it and running 'npm install' from inside that theme directory afterward. This put the node_modules folder inside the Understrap theme directory instead of the reverse, which is nice, but BrowserSync and Gulp Watch no longer worked.
