### ISSUE TITLE
Gulpfile missing bootstrap required packages

### ISSUE THREAD

**Issue by eberhapa** [understrap/understrap#380]
Is there a reason why there is no Autoprefixer and postcss-flexbugs-fixes package like the bootstrap documentation requires it? 

> Want to compile Bootstrap with your project’s asset pipeline? Choose this option to download our source Sass, JavaScript, and documentation files. Requires a Sass compiler, Autoprefixer, postcss-flexbugs-fixes, and some setup.
https://v4-alpha.getbootstrap.com/getting-started/download/

Edit: I've seen the other issue which is marked as resolved. But why the autoprefixer isn't added to the repo?

Thanks

**Comment by axlright** [comment]
Closing this issue due to no comments in over six months, and due to Bootstrap 4.0.0 updating requirements as listed [here](https://getbootstrap.com/docs/4.0/getting-started/download/#source-files) to only require an Autoprefixer, which has been added to Understrap.

Comment if the issue persists and issue can be re-opened.
