### ISSUE TITLE
Adding additional JavaScript files

### ISSUE THREAD

**Issue by dylannirvana** [understrap/understrap#492]
What is the best way to add additional scripts? I wanted to add smooth scrolling (which I thought might already be included, but not sure where). Wasn't sure if I should add the path in the gulpfile after `basePaths.dev + 'js/bootstrap4/bootstrap.js'` (line 201) , or after `// Copy Popper JS files` (line 261).

**Comment by axlright** [comment]
My understanding is that smooth scrolling requires the full jQuery not jQuery slim. I build a lot of websites with smooth scrolling and I swap out versions of jQuery in the functions.php file and load up the full jQuery for those websites.

The `basePaths.dev` is referencing the `/src/` directory, and within that is the file you're referencing.

**Comment by shansmith01** [comment]
I have used this library https://github.com/cferdinandi/smooth-scroll which seems to work fine and uses slim

I add the library via NPM. and added this under popper.js

    gulp.src(basePaths.node + 'smooth-scroll/dist/js/smooth-scroll.min.js')
        .pipe(gulp.dest(basePaths.js));

    gulp.src(basePaths.node + 'smooth-scroll/dist/js/smooth-scroll.js')
        .pipe(gulp.dest(basePaths.js));

**Comment by Thomas-A-Reinert** [comment]
Hi @dylannirvana  - afaik Bootstrap 4 does not include any smooth scrolling. So you´d have to add that as an own dependency.

Feel free to do so by throwing in the .js library into your src/js folder and adding it into the gulpfile.js between the lines
` // End - All BS4 stuff
 paths.dev + '/js/skip-link-focus-fix.js',

 // Adding currently empty javascript file to add on for your own themes´ customizations

 // Please add any customizations to this .js file only!

 paths.dev + '/js/custom-javascript.js'`

I´d personally link the library/plugin _before_ the custom-javascript.js  - the latter should contain it´s configuration only.

I´ll close this issue as it should hopefully be fixed by now then. Feel free to re-open if not, okay?
