### ISSUE TITLE
Undefined variable when overriding in _child_theme_variables.scss

### ISSUE THREAD

**Issue by christopherarter** [understrap/understrap#515]
I just fixed an issue others may have in the future: I'm getting an error on running the `watch` tasks, `Error: Undefined variable: "$gray-600". on line 14 of sass/theme/_child_theme_variables.scss`.

It's because `child_theme.scss` is importing the variables _first_, then bootstrap. I moved the import of the variables to a proceeding line and it fixed it.  Right now, this is working perfectly:

    @import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Change from 
    /bootstrap3 to /bootstrap4 Watch out! just for testing in the moment!
    @import "../src/sass/understrap/understrap/understrap";// <-------- Loads the UnderStrap 
    defaults. Just a few classes to incorporate BS in WP
    @import "../src/sass/understrap/theme/contact-form7";// <-------- Loads some basic styling 
    for contact form 7 plugin

    //Optional files - If you don´t use the corresponding scripts/fonts comment em out
    @import "assets/font-awesome"; // <------- Font Awesome Icon font
    @import "assets/underscores"; // <------- Underscores media styles
    
    @import "theme/child_theme_variables";  // <--------- Add your variables into this file. Also add 
    variables to overwrite Bootstrap variables here

    // Any additional imported files //
    @import "theme/child_theme";  // <--------- Add your styles into this file

Just a heads up!

**Comment by axlright** [comment]
Thanks for the input @christopherarter - many people keep the _child_theme_variables first because they want to re-declare global variables there, for example to change what color `$gray-600` specifies to not use the default Bootstrap color. If you reference Bootstrap variables in your `_child_theme_variables.scss` you will have to declare them earlier in the file or do what you did here and move your _child_theme_variables later in the Sass compiling order. 

Glad you found a solution that works for your needs.

Closing this issue.
