### ISSUE TITLE
More Customizer options for text and link-colors

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [understrap/understrap#582]
Well, everything said in the topic. Text-color and "primary" as well as "primary":hover can be set there now.

Anyway, there´s an issue I cannot resolve. Try to set full red for hover color for example (#ff0000). It will not get displayed. It WILL in the customizer preview but NOT on the live site. There, it will be darkened to an extent where you will not be able to recognize the original, set color. Yes, this is a dupe to https://github.com/understrap/understrap/pull/581 but something went terribly wrong commiting, so I set up the whole *** shit totally anew...

Can anyone shed some light on the why´s and how-to-fix-thems?

**Comment by Thomas-A-Reinert** [comment]
Please test first. I will not merge that one before it has been tested thoroughly

**Comment by MarieComet** [comment]
Just added a custom hover primary color and it works fine both in customizer and live site : 

![image](https://user-images.githubusercontent.com/7976501/36932793-19a06b08-1ecf-11e8-8223-b04b596e2032.png)

![image](https://user-images.githubusercontent.com/7976501/36932798-2b4b54c6-1ecf-11e8-952b-1ce66bce320d.png)

**Comment by holger1411** [comment]
Sorry that I have to say that (you put a lot of time in it and I really appreciate it): But baiscally I would vote against such an option.

UnderStrap is made primarily for developers who design WordPress websites for endusers.
Developers don´t need such an option (because they use the SASS variables) and most of them don´t want to give there customers the change to overwrite carefully selected colors by there own.
So there is a change that they remove it or tell there customers not to use it.

The only use case for this option is for developers of commercial themes (for themeforest.com etc.) where such an option can be used as additional feature to promote the theme to endusers.
But in this case this developers should be responsible for this features. Especially if they earn money with it.

My experience: Even a small feature need constant maintanance. That means someone need to monitor it. Keep it inline with Bootstrap and WordPress. Test it in combination with other option and setups and browsers, create bugfixes etc.
Can cost a lot of time, especially over the years. 
Time which can´t be spend for other "must haves".

Thats only worth it if it is a core feature needed and used by the majority of WordPress theme developers (not end users).

Thats just my two cent´s and if there are good reasons that theme developers need such a feature we should add it (....but you have to convince me that the pro is bigger than the con). 

Alterntatively: You can create a branch here on UnderStrap with your changes. So we can keep it outside the main project but everyone can use and test it.

**Comment by Thomas-A-Reinert** [comment]
@MarieComet  thx for testing. It also works on my local environment now, magically.. Maybe it was just too late ;)

@holger1411 not a problem at all. Not too much time "wasted" - in fact I learned something. And I totally understand your confinements with your intentions explained. So I´ll just withdraw my commit.
I think forking it or maintaining a branch for that small thing is not really an option - it would have to be maintained too..

**Comment by axlright** [comment]
Thanks @Thomas-A-Reinert and @holger1411 for all the work. 

Closed issue but I'm personally interested in it. I'd like to learn more about how to add front-end customizer options that a client can actually use to change some styling. I totally get what @holger1411 is saying, and this is true for 90% of jobs. But when I make websites for people who are themselves designers (or think they are), sometimes the client wants to fiddle around with certain colors etc. 

Either they email me 100 times in a row or I can add a customizer for a few options and let them keep themselves busy.

This is a different issue than providing a customizer for everyone to use. But adding to the list of 100 things I want to learn, I think it'd be cool to add and use customizer options on certain jobs.

Thanks for all your work!

**Comment by Thomas-A-Reinert** [comment]
@axlright not worth mentioning it, just trying to contribute a little ;)

Just check https://github.com/understrap/understrap/pull/581/commits/d700fe52657122852fc25740293e46da7af75ddc to get a quick start. It adds the customizer controls for above mentioned and injects them via the js. Missing there is an add on to inject these settings in the `<head>`-section/a custom `<style>` section. These would go into header.php.

**Comment by Thomas-A-Reinert** [comment]
Sidenote: If you want to really, _really_ get the hell out of customizer settings the easy(er) way with custom controls, I´d recommend taking a look at the [Kirki Customizer Framework](http://aristath.github.io/kirki/). I integrated 100+ settings with it in my own Understrap(3)-based "[CustoMaterial](https://github.com/Thomas-A-Reinert/CustoMaterial)" theme which I honestly never really finished, but still use as a base for quick jobs here and there.

**Comment by axlright** [comment]
@Thomas-A-Reinert awesome - thanks. I wonder how that will conflict with adding Critical CSS into the header. Just wrote [a big blog post](https://alexwright.net/web-design-secrets/how-to-use-critical-css/) about that. I'd imagine the two wouldn't play nice, or if they do, there may end up being a lot of CSS in the header with the CSS from the customizer added lower in the `<head>`

Either way, I'll check it out - thanks!

**Comment by Thomas-A-Reinert** [comment]
Yeap, I guess they won´t play nice together. But i cannot figure out a nice workaround though. CritCSS can only be used/set up correctly when there are no variables, U guess.

**Comment by gtermini** [comment]
Too bad this features was not included. We are building a theme based on Understrap, which will be used on various institutional websites, which have their own branding and colors. For us, having an option like this one, will reduce the amount of work and will consolidate the ecosystem. We are adding it back, so that we can use ONE theme to "rule" all the websites we manage.
