### ISSUE TITLE
No padding inside TinyMCE editor window

### ISSUE THREAD

**Issue by webbyhall** [understrap/understrap#600]
Please delete anything that does not apply for you!

## I'm submitting a ...
  - [ ] bug report
 

## Please tell us about your environment:

  - WordPress Version: 4.9.4
  - Browser: [ all ]

There seems to be no padding within the window on the TinyMCE editor, so any written content is placed tight against the window border. This seems to be the case for Understrap itself and the child theme.

![tinymce](https://user-images.githubusercontent.com/5443475/37520765-3e9ae5f4-2916-11e8-8f9b-206a3e08ca30.gif)

**Comment by Thomas-A-Reinert** [comment]
Thanks for submitting this issue, @webbyhall .

It seemed easy but digging deeper into this issue, it seems to become overly complex.

Why is that? Reasons:

1. The custom-editor-style.css gets generated from your *.scss files upon the gulp "scss-for-prod" and "gulp sass" tasks.
2. So whatever I´ll write into the source scss-files will define the frontend-display as well as the backend (editor) display.
3. Only solution - as it seems so far - is to import the generated files and overwrite them (at least the body-margin) with another css file just made for the backend TINYMCE-editor.
4. This works in my dev-environment. What I cannot really tell so far is what happens if it get´s deployed in the "dist"-folder when running the "gulp dist" or "gulp clean-dist" tasks. But I´m not the gulp-guru so I´ll leave that open for others.

Interim conclusion: It seems to work like intended but needs further testing/investigation. I´ll therefore just push that to new newly established "development" branch in a second.

@axlright and @0dp - you may want to investigate that? Thanks in advance!

**Comment by holger1411** [comment]
Hm, Its a good question...

I add the full themes css file as editor style some time ago. The reason was that you can build up complex Bootstrap based layouts in your editor with all the .cols .row etc. and you can see and review it right in your editor.
Especially if it is used with the blank.php or empty.php template you can build complete landingpages and complex structurs without leaving the backend editor.
But I don´t know if it is a common usecase and if it makes sense to maintain it. Especially with Gutenberg around the corner ...

The approach for this case would be (from my point of view) to genereate a css/editor.css file from a sass/editor.scss fill which @import ´s the whole theme.scss plus an extra _editor.scss file. Sounds complex but so we can provide all themes styles plus some editor-only css.

The other option: 
We just remove the editors extra styles from inc/editor.php and /css

**Comment by axlright** [comment]
I figured that `custom-editor-style.css` was for the TinyMCE editor but never gave it much attention. I've noticed there's no decent `<blockquote>` support (at least on my installs) and it would be nice for my clients to see some version of what they are laying out in the TinyMCE editor.

I'd be interested in working on this a bit, though I agree with @holger1411 that with Gutenberg around the corner, we should be using as much of the small amount of developer resources towards this rather than supporting what will become a legacy editor.

There's a middle ground in what @holger1411 suggests. It seems too bad that all of the front end stylesheets need to be loaded in addition to a `css/editor.css` file, but I guess that's required to get the grid framework etc.

I'm happy to help with this, but I'd recommend not going super far with it.

**Comment by roman-soerensen** [comment]
@webbyhall : I just added 

`body#tinymce {
  padding-left  : 15px !important;
  padding-right : 15px !important;
}`

as a workaround to my custom css

**Comment by holger1411** [comment]
So the solution would be "all-in" or nothing...

Okay, I add a custom-editor-style.scss file into the /sass folder.
It will generate a custom-editor-style.css file in the /css folder which will be used in your editor integrated via inc/editor.php
My commit: https://github.com/understrap/understrap/commit/0640bf70946c35766978c1db1b9732853c78f6eb

The sass file is empty by default. But you can import everything with adding just:
`@import "theme"; `
to it.
And you can add own styles on top if necessary.
Or just some own styles but without the whole Bootstrap stuff.
Or just some basic Bootstrap stuff like the grid via @import 

I keep it empty by default because it may break the editor depending on your changes to the Bootstrap variables. 
For example you have a dark text color and a dark body background color but uses .containers or .rows with white background on your website, the editor will just use the body background and the text color. So you have a dakr backgorund color and a dark text color...

So we avoid such problems by keeping the editor file empty. But it is relatively simple for developers to customize the file and add styles if needed.

**Comment by 0dp** [comment]
Since everything is being included in custom-editor-style.css, I can track the missing margin back to line 15 in custom-editor-style.css. (normalize) Removing that fixes the missing margin issue.

So what is the solution? Well according to the cookbook we should empty the content of custom-editor-styles.css and give the user the ability in the docs to include the theme.min.css in inc/editor.php.
This does fix the issue with browser reset half way down the page, but now the developer knows what they have done and can compensate. Another solution that builds on top of this is to have a minimum of required styling in custom-editor-style.css and/or create a new gulp task that compensates. But cookbook says no :)

**Comment by holger1411** [comment]
@0dp  See my comment above and my commit https://github.com/understrap/understrap/commit/0640bf70946c35766978c1db1b9732853c78f6eb
;-)

**Comment by holger1411** [comment]
So you have an easy way to add everything you need (including parts from Bootstrap, variables, your own variables etc.) by editing sass/custom-editor-styles.scss, but by default for "out-of-the-box" UnderStrap users, nothing will happens.

Maybe we can just add the font-family from its variable. 
So we have a sample of how you could edit the apperance of your editor in a safe way.

**Comment by 0dp** [comment]
I think I took to long to write my comment @holger1411 :)

I've just tested your commit, looks good

**Comment by holger1411** [comment]
Closing this issue becasue it was fixed and shipped with 0.8.2
