### ISSUE TITLE
Running custom js

### ISSUE THREAD

**Issue by mherda** [understrap/understrap#602]
Hi,

I have added a file (.js) to js/ directory. As gulp watch is running it has run 'gulp scripts'. As my file is in js/ directory, I assume I don't need to change anything in gulpfile as the path is the same. Yet my code does not run. For testing purposes, I just included: alert("hello"); in my .js file.

What else do I need to do?

Also, Would you be able to add support for ES6 compiling to your great package?

Thank you

---

---

### For which *Section* would you like to suggest a proposal?
Please see currently planned/completed sections and their current status in [README.md](https://github.com/Thomas-A-Reinert/WordPress-Developer-Checklist/blob/master/README.md)

### *What* would you like to suggest / improve?
Please try to find at least two sources that confirm your proposal. Include URLs.

**Comment by ZacharyElkins** [comment]
Hello.

Gulp does not pull in any file, it pulls in specific files and outputs them where you have placed your custom file. 

Please refer to my comment here for instruction:
https://github.com/understrap/understrap/issues/548

Issue #548

**Comment by Thomas-A-Reinert** [comment]
Please see #593 and #602 as duplicates of this issue.

Sidenote: Why does it not just include any *.js by default? Because the order in which they may be included may become an issue. So just keep the needed order in custom-javascript.js and you should be good to go ;)

Closing this issue as it should be finally resolved now. Feel free to re-open if the problem persists, okay?

**Comment by mherda** [comment]
Thanks but I'm still at loss.

```
// Uglifies and concat all JS files into one
gulp.task( 'scripts', function() {
    var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',
        paths.dev + '/js/custom.js'
    ];
```
The content of custom.js is just: alert("hello");

The file custom.js is in src/js/ just alongside skip-link-focus-fix.js

Yet, it does not seem to work. I've opened Chrome's developer's tools but there's no error message.
Gulp Watch just outputs: Starting 'scripts' .... Finished 'scripts' each time I save a file. So no errors there.
Please advise. Thank you.

**Comment by axlright** [comment]
@mherda `gulp watch` doesn't compile js scripts - it only watches for sass changes. You need to run `gulp scripts` each time you want to re-compile the scripts. Have you tried that?

**Comment by Thomas-A-Reinert** [comment]
@axlright nope you don´t ;) just run "gulp watch-bs" and it will compile (nearly) everything.

I just added the `alert("hello");` to custom-javascript.js and it shows the following without any console errors or the likes.

![image](https://user-images.githubusercontent.com/5886977/37560620-4ec54db2-2a3c-11e8-9554-ec425c7c2fee.png)

**Comment by mherda** [comment]
Thanks guys - having run gulp watch-bs, it's working fine.

**Comment by Thomas-A-Reinert** [comment]
Thanks for letting us know, @mherda ! Glad we could solve your issue!

**Comment by axlright** [comment]
Oh, okay. I never run the `-bs` part because the Sass maps don't work. It's my understanding that `gulp watch` does not compile js - is that correct @Thomas-A-Reinert ?

**Comment by Thomas-A-Reinert** [comment]
Cannot confirm @axlright - because I never really ran gulp watch ;)

**Comment by Thomas-A-Reinert** [comment]
Sidenote: I really do not rely on .map files. I tend to inspect via dev-tools only.
But if that is really the case - they work when you run a `gulp watch` task and DON´t when you run a `gulp watch-bs` this is definitely an issue that has to be attended!

**Comment by axlright** [comment]
Sidenote! I use sass maps a lot - so much that I put through a Pull Request to fix them with Understrap Child. Dev tools is great, but I need to know which line of which sass file generated which css. 

I'll have a look into why there's a difference. I only ever use `gulp watch` because that's what runs my working maps functionality.

**Comment by Thomas-A-Reinert** [comment]
Well, my SASS is usually very pretty well sorted (following the BEM rule) so that I get rarely confused. 

@mherda: Sorry that you probably get "spammed" with comments right now. But please bear with us - we´re trying to improve ;)

@axlright you´re okay if I assign that task to you and @0dp - as you´re the gulp-heroes in our team? *friendlysmile* I´ll do anyway right now, but please keep me updated if you want to refrain from that, okay? :P

**Comment by Alligatore3** [comment]
Hi guys,

disclaimer: I'm already using _**gulp watch-bs**_

This is my code:
 ```
$( document ).ready(function() {
  console.log(300)
  /**
   * {@link https://stackoverflow.com/a/1145297}
   */
  $("to-top").click(function() {
    $("html, body").animate({ scrollTop: 0 }, "slow");
    return false;
  });
});

console.log(3000)
```

File location => `wp-content/themes/tedx/src/js/tedx.js`

Gulpfile:
```
// Run:
// gulp scripts.
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
	var scripts = [
		// Start - All BS4 stuff
		`${paths.dev}/js/bootstrap4/bootstrap.bundle.js`,

		// End - All BS4 stuff

		`${paths.dev}/js/skip-link-focus-fix.js`,

		// Adding currently empty javascript file to add on for your own themes´ customizations
		// Please add any customizations to this .js file only!
		`${paths.dev}/js/tedx.js`
	];
```

**PROBLEM:** => No logs in my console. Am I missing something ?
Thanks

**Comment by Tiex84** [comment]
Hi @Alligatore3 
Try this:
Stop gulp watch
Replacing `$` with `jQuery `in your js file
Re run gulp watch

**Comment by Alligatore3** [comment]
Ehy @Tiex84 

I tried but no progress.
I don't think it's naming issue indeed you can see a console statement **outside** _.ready_ method, at least that one I should see it

**Comment by Alligatore3** [comment]
@axlright @ZacharyElkins 

Any ideas ? I'm stuck.

**Comment by Alligatore3** [comment]
UPDATE:

looking in my network and filtering by JS, I do not see my theme.min.js
So moving inside `inc/enqueue.php` you can find this line
```
wp_enqueue_script( 'understrap-scripts', get_template_directory_uri() . '/js/theme.min.js', array(), $js_version, true );
```
Changing $in_footer parameters from true to false causes the missing `theme.min.js` being included.
[wp_enqueue_script](https://developer.wordpress.org/reference/functions/wp_enqueue_script/#parameters)

Of course this doesn't fix the problem because jQuery'll always included after.

**Comment by axlright** [comment]
How about `gulp scripts`? This is what I run to compile js.

The recommended workflow is to add your js to a file called `custom-javascript.js` in `/src/js/` and include it via these lines in `gulpfile.js`

```
		// Adding currently empty javascript file to add on for your own themes´ customizations
		// Please add any customizations to this .js file only!
		`${paths.dev}/js/custom-javascript.js`
```
