### ISSUE TITLE
Change mobile toggler breakpoint to medium breakpoint (48-61em)

### ISSUE THREAD

**Issue by amandablum** [understrap/understrap#614]
Pretty simple- having trouble doing this via css because of aria. Would like to enable the toggler on everything south of 62em.  Probably a very simple solution that I haven't arrived at. Help appreciated.  ##

**Comment by Thomas-A-Reinert** [comment]
Hi Amanda,

please check the Bootstrap 4 Tutorial for that request: https://getbootstrap.com/docs/4.0/components/navbar/?#responsive-behaviors

If you need to override on of BS4´s built in breakpoints check for the classes in the scss-files and build up on these..

Hope it helps. As this issue is more related to Bootstrap or overriding Bootstrap in general than UnderStrap-Code/-Functionality, I´m going to close this. Please leave a note if that helped solving your issue.

Thanks in advance!
