### ISSUE TITLE
2 Previous and Next buttons on pagination

### ISSUE THREAD

**Issue by mernoid** [understrap/understrap#618]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] I need help

## Please tell us about your environment:

  - WordPress Version: 4.9.x
  - OS Version: [Windows 7 ]
  - Browser: [ Chrome XX  ]
  - Language: [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
---

My post pagination shows two next and previous buttons. See the screenshot:
![image](https://user-images.githubusercontent.com/37874682/38036490-6e60e47a-32c4-11e8-9447-65f47acca01a.png)

The question marks are font awesome icons that got converted to "?" because Notepad++ doesn't support them.

**Comment by Thomas-A-Reinert** [comment]
I´m sorry, i can´t reproduce that problem. See 
![image](https://user-images.githubusercontent.com/5886977/38055761-ea139fe8-32da-11e8-8e4d-825842215cd3.png)

* Can you provide a link so I may inspect the resulting code?
* Did you change anything within the code, because this does not seem to be the default behavior?
* Are you using the latest UnderStrap version? (Try to setup a fresh install and use the latest versions to compare).
* Are you using a Child-Theme?



[Sidenote: Notepad++ is kinda.. well let´s just say: there is a whole lot of free available editors that are a LOT better these days! Just my personal opinion, but in descending order these are: Visual Studio Code, Brackets, Atom, Sublime Text 3]

**Comment by mernoid** [comment]
Here's the link: yourfreecoin.com/theme
I did change a few templates but never touched the Pagination template. I changed the Previous and Next Post template below Single posts to remove font awesome icons, btw.

Yes, the latest version. I'll try that.

No, the parent theme.

Thanks, I'll give Visual Studio Code a try.

**Comment by Thomas-A-Reinert** [comment]
Ah, now I understand. There are not two next/previous buttons. The inner buttons (which get displayed correctly) are in fact next/previous buttons. The outer ones jump to the first/last page ;)

Up to you to delete those and/or give them your own icons.

I´ll mark this issue as solved, feel free to reopen if the problem persists.
