### ISSUE TITLE
js require() does not work

### ISSUE THREAD

**Issue by mherda** [understrap/understrap#627]
Hi,

I've installed 'strava' via npm and would like to get authenticated:

```
var strava = new require("./strava")({
        client_id: "<Client ID>",	
        client_secret: "<Client Secret>",
        redirect_uri: "<Redirect URI>",
        access_token: "<Access Token>"
    });
```
I get the following error in the console
ReferenceError: require is not defined

I have googled it and understand that require() is part of node and cannot be run in a browser. People recommend Browserify to get things like that running.
Is there any way to easily bundle it with the existing understrap setup to make it run?

Thanks

**Comment by Thomas-A-Reinert** [comment]
What is "strava"?! Why does it need a client id/client secret/redirect url/access token?

Could you please clarify, because my crystal ball is on vacation.. :/

**Comment by mherda** [comment]
Apologies.

Strava is a portal where runners/cyclists record their activities using a variety of electronic devices that record the data. So basically, it's like Facebook but for sports people with lots of numerical data that is displayed. Users can join clubs etc. I'd like to pull some statistics for our club.

The npm package is here:
https://www.npmjs.com/package/strava

Official Strava API docs:
https://developers.strava.com/

**Comment by mherda** [comment]
Sorry, it needs the access token, I guess to authenticate user so because the data is not public. The access token is generated in my account settings so that's not the problem.

**Comment by Thomas-A-Reinert** [comment]
Please understand that we cannot supply support for 3rd party services. I´d recommend contacting the npm package maintainer.

**Comment by mherda** [comment]
Thanks Thomas.

so are you saying that normally in the current setup the function 'require()' is not a problem? It's just this particular npm package is the problem?

**Comment by 0dp** [comment]
hey @mherda you cannot simply install a node package and expect it to work in an arbitrary context (UnderStrap)

UnderStrap is a WordPress theme that uses a node based task runner, and npm for installing and managing dependencies.

The "require" method is built into node, hence gulp. But require method is not a part of the theme nor a part of ECMA(current standard) or jQuery. So that's where your journey starts(requireJS, commonJS, ES6). whats next? We don't know, that's why @Thomas-A-Reinert say we can't give people support for third party packages.

> so are you saying that normally in the current setup the function 'require()' is not a problem? It's just this particular npm package is the problem?

There is no require function in the theme UnderStrap. There is probably no problems with the strava package, you are just not using it correctly in this context.
