### ISSUE TITLE
Update both Parent theme and Child theme to use Bootstrap 4

### ISSUE THREAD

**Issue by dbybanez** [understrap/understrap#632]
## Issue is about..
  - [ x ] a Question
  - [ x ] I need help

## Please tell us about your environment:

  - WordPress Version: 4.9.5
  - OS Version: Windows 10 
  - Browser: All
  - Language: PHP, MySQL, HTML, S/CSS, JavaSript, jQuery
  - Node.js & NPM Versions: Node.js v8.1.3 | NPM 5.1.0

---

Hi, 

I'm using UnderStrap v0.6.5 and the child theme v0.3.2. I wanted to update both the parent theme and child theme so I could use Bootstrap 4. Is there any documentation on how to migrate? Or any suggestions on how to migrate to Bootstrap 4?

Thanks,
David

**Comment by axlright** [comment]
Hey @dbybanez in your case, since the change from child theme 0.3.2 to 0.5.1 is a big step, I'd recommend the following:

First update just the child theme. The parent theme contains all the php files but the styles and scripts for things like Bootstrap are all self contained in the child theme.

Copy the following files from the repo's child theme 0.5.1 into your child theme
gulpconfig.json
gulpfile.js
package.json

run `npm install` and make sure `gulp copy-assets` runs at the end of that process - it should automatically. Then run `gulp scripts` and `gulp styles` and you should be good to go. I'd then change the theme version number in your `style.css` to keep reference on where you are.

If / once that all works, I'd update the parent theme. You'll probably need to adjust some of your function names in your child theme `functions.php` and most likely the `new understrap_WP_Bootstrap_Navwalker(),` in your child theme `header.php` needs to updated.

Hope that helps.

**Comment by holger1411** [comment]
And, if you use Bootstrap3 markup in your child theme .php files you have to adjust it.
Here is a migration doc:
https://getbootstrap.com/docs/4.0/migration/

**Comment by pattonwebz** [comment]
Shameless plug here but the `understrap_WP_Bootstrap_Navwalker()` walker is based on a an old version of the [WP_Bootstrap_Navwalker](https://github.com/wp-bootstrap/wp-bootstrap-navwalker) that Ed, myself and a few other developers have maintained over the years. I have not tested the walker in this theme however the version which it was forked from did not have support for BS4 markup anyway.

The latest version of the walker at our repo supports bootstrap 4 (but does bring some breaking changes due to he corrected link-mod and icon class handling).

**Comment by axlright** [comment]
@pattonwebz Thanks - this is pretty rad and totally worth the plug. @holger1411 @Thomas-A-Reinert should we look into making another round of updates to the nav walker?

**Comment by 0dp** [comment]
#567

**Comment by 0dp** [comment]
@pattonwebz @axlright I just quickly tried to plug the newest walker into the theme but couldn't get the dropdowns to work. I had a really long day so I am not going to debug tonight. But if you get the chance, give it a shot 🙏 👊

**Comment by pattonwebz** [comment]
I made a quick PR with the other walker and the depth parameter. Is working my end with dropdowns, can you test it on yours when you get a chance?

**Comment by Thomas-A-Reinert** [comment]
thanks @pattonwebz for joining in!

Tried to integrate your latest bs4 version bout a month ago but miserably failed and lost patience in doing so, cos thought this would be a no-brainer :/ May have been due to https://github.com/understrap/understrap/issues/632#issuecomment-381754566 though.

As I´m currently working on a new project that relies on the navigation to have css classes (yes, Font-Awesome in this case for some socialmedia icons) and NO text to SHOW BUT needed to be available for accessibility purposes we´d need to rework the nav-walker as a whole in my eyes which would prolly benefit every dev, not just me ;)

The situation as follows:
![image](https://user-images.githubusercontent.com/5886977/38839147-9c66bae2-41d9-11e8-8354-e5b3b071a027.png)

1. I can´t leave the "Navigation label" empty as WP seems to erase/not render any Menu entry without it.
2. Can´t fill it or it will get rendered.
3. Leaving an &nbsp; is an - ugly - workaround which works to render the menu entry.
4. Anyway, it leaves no chance to render an accessible text alternative through a .sr-only class or comparable.

Possible solution:
1. Wrap the Navigation label in _any_ class that can be addressed via CSS and therefore be hidden for non-visually impaired user.

**Comment by pattonwebz** [comment]
The latest version of the walker I added in PR #647 should be able to do what you need. Just add a `sr-only` class the the `CSS Classes` input beside any `fa fa-*` classes and you should be good. Navigation label should be supported too :)

**Comment by pattonwebz** [comment]
@Thomas-A-Reinert would the fact that icons are output with the `aria-hidden="true"` property cause issues with your intended use case?

**Comment by pattonwebz** [comment]
So I misrepresented the method above but it actually shows 2 different functions of the walker. 

1. 1st thing it shows is that icons are added via the 'CSS classes' input and then at output time they separated and placed on their own `<i>` element.
2. 2nd thing it shows is that items can be made _icon only_ by adding some icon classes alongside the `sr-only` class to the item in the CSS classes input. On output the sr-only class wraps only the text used as the label and allows the icon to remain on display (albeit with a `aria-hidden="true"` parameter - which seems not ideal for icon only items but is fine for any items which are icons + text).

The label text is not hidden by default - it is only hidden because of me adding the `sr-only` class to the item. You can have a mix of various icon only, text only or icon + text items as you choose. 

You can also use the `dropdown-header`, `dropdown-divider`, `dropdown-item-text` or `disabled` classes on items and the walker will handle them as Bootstrap markup requires, outputting different elements where required :)

**Comment by Thomas-A-Reinert** [comment]
@pattonwebz another night-shifter ;)
Thanks again for your fast and helpful updates! Invaluable!
(Please excuse me, but I´m no native english, but I´ll try to get along though)

1. Yeap, absolutely correct! Anyway, personally I HATE putting them into an `<i>`-element. That ain´t made for it, I´d prefer a `<span>` and I know that certain WCAG-Tools punish putting Icons into an `<i>`-Element.. But that´s not really elementary for the whole thing to work as intended...
2. I guess I´d have to check that out live. Don´t know if I understand you correctly in that case.
Yes, accessibility can still be improved, you´re absolutely right. That was just a quick fix. Not meant to stay forever and I´ll set up an improved solution for that..

Again - thanks for joining and your engagement. Priceless. Is there any reason  we´d get you aboard? :)

**Comment by pattonwebz** [comment]
Your English is actually quite good, my explanations are not so good haha!

As for swapping the `<i>` element to a `<span>` The current walker cannot do that but it would be quite easy to add a flag and let people choose which they prefered. We can also work to get accessibility improved too in the same batch of updates.

When you say:
> Is there any reason we´d get you aboard? :)

Do you mean
* You want to know how I found this project?
    * I spotted it being updated at wordpress.org (I am a member of the official wordpress.org Theme Review Team) and was just curious so I stopped by. I seen this issue and though I could help out so I commented.
* You want to know if I am interested in joining aboard the project.
    * I am here to offer any assistance I can and am onboard if the team wants me :)

**Comment by pattonwebz** [comment]
@Thomas-A-Reinert The PR i made has the latest version of the walker in it so you should be good to pull it to a dev environment and test it out. You just need to add your menu through the WP interface and set the options you want - like icons, screen reader etc. Feel free to ask any question you have when you get to testing :)

Don't worry about misunderstandings about mentions of the team. I know you were not asking me to join, and I was not requesting to join. Just here offering help to you guys if I can  :smile:

And to be clear I am *an active member* of Theme Review team but I am not representing the team here. I only speak for and represent myself.

**Comment by 0dp** [comment]
This was a pleasant surprise to wake up to. Gotta love the community.
I'll give the pr a test this afternoon and report back 👍

**Comment by Thomas-A-Reinert** [comment]
Hi @pattonwebz - I thoroughly tested your PR and found just two issues with it. 

**Issue 1**  You `require get_template_directory() . '/inc/class-bootstrap-wp-navwalker.php';` but the files actual name is class-wp-bootstrap-navwalker.php so it throws an error that the file couldn´t be found.

**Issue 2** I´d recommend keeping the old functions name `understrap_WP_Bootstrap_Navwalker()` instead of renaming it to `WP_Bootstrap_Navwalker()`, because if you already use a child-theme it will probably just render a white page pon update due to the missing function as it did in my test-scenario. This will probably cause a lot of (avoidable) confusion with end-users.

Apart from that everything works like a charm! Thanks a LOT for that!
Would you be willing to fix those two things and issue another pull request for it then?

**Comment by pattonwebz** [comment]
@Thomas-A-Reinert Yep I will look to fix both those issues, my bad. I really should have created the PR from the live environment I work in instead of manually duping the changes over to a fresh repo.

PR update will be through in the next hourish :)

**Comment by Thomas-A-Reinert** [comment]
Currently working on another child-theme I can confirm that dropdowns also work with the latest commit @0dp ;)

Thanks again for your help, @pattonwebz !

**Comment by Thomas-A-Reinert** [comment]
Closing that issue due to the fact that it became a TOTAL a spin off of  the orginal topic that _may_ have been resolved in the meantime. Feel free to open up another issue that we´re NOT going to hijack this time, okay?
