### ISSUE TITLE
Grouped Product Children Not Showing

### ISSUE THREAD

**Issue by olivern** [understrap/understrap#639]
I have been using understrap for some time but not with any woocommerce stores. I have recently redesigned a website using understrap and noticed that after moving the content, the grouped product is now not showing any options on the product page. When you click "add to cart" it says "please select an option" but the options are not there.  The grouped product and its child products are set up exactly as they were on the old site where it was working.  Haven't made any template changes to woocommerce. I am wondering if this is an understrap issue or something else.

## Issue is about..
  - [ ] a Bug Report
  - [ ] I need help

WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.3
Name: UnderStrap Child
Version: 0.3.5

**Comment by Thomas-A-Reinert** [comment]
Hi @olivern , doesn´t really sound as if it was UnderStrap related due to the fact that UnderStrap just has some WooCommerce-templates but does not rewrite anything of Woo´s structure/database/functions.
To me it seems as if anything wasn´t correctly re-written when moving the site.

Please install the "[Duplicator](https://wordpress.org/plugins/duplicator/)" plugin on your old site and make a backup with it. It will give you an installer.php and a zip-file that you should upload to your new server. Once uploaded call the installer.php. It will give you a wizard where you need to enter info about new db-connection etc. and then unpack and rewrite _every_ path in the database. Please try that - it will probably give better results than a manual relocation.

**Comment by olivern** [comment]
Alright, thanks. I was thinking that it probably wasn't under-strap but just wanted to check.
