### ISSUE TITLE
Rolled back update and now having issues with jquery.slim.min.js

### ISSUE THREAD

**Issue by erinjohnson21** [understrap/understrap#643]
I am using the latest update to Wordpress. I also updated UnderStrap to the latest version but it broke my site. The only thing that was showing was the nav bar with logo and external links. Everything else was missing.

So I rolled back from a previous backup and now my jQuery is not loading properly and it is keeping certain plugins from loading. 

![screen shot 2018-04-14 at 10 56 46 am](https://user-images.githubusercontent.com/13616831/38770073-bfcd0a9e-3fd2-11e8-9109-387f9d18336f.png)

How can I upgrade to the new theme and ensure it doesn’t break my site (I use a child theme) or replace the jQuery in my current theme.

Thanks

**Comment by axlright** [comment]
Regarding the issue of "The only thing that was showing was the nav bar with logo and external links", make sure that your header.php is using the new nav walker:
`'walker' => new understrap_WP_Bootstrap_Navwalker(),`

Regarding jQuery, can you send details of the child theme's function.php enqueue lines for jQuery? Newer versions of the themes don't call jQuery slim.

**Comment by erinjohnson21** [comment]
This is the child theme which is Version: 0.3.1
`function understrap_remove_scripts() {
    wp_dequeue_style( 'understrap-styles' );
    wp_deregister_style( 'understrap-styles' );

    wp_dequeue_script( 'understrap-scripts' );
    wp_deregister_script( 'understrap-scripts' );
}
add_action( 'wp_enqueue_scripts', 'understrap_remove_scripts', 20 );

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {

	// Get the theme data
	$the_theme = wp_get_theme();

    wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.css', array(), $the_theme->get( 'Version' ) );
    wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/child-theme.min.js', array(), $the_theme->get( 'Version' ), true );
}`

I am using the Understrap theme Version: 0.6.7

**Comment by axlright** [comment]
@erinjohnson21 Which version of the child theme have you upgraded to?

It may be a good idea to make sure you're using the current child theme's functions for enqueuing jQuery. Here's the functions from the most current child theme's functions.php:

```
function understrap_remove_scripts() {
	wp_dequeue_style( 'understrap-styles' );
	wp_deregister_style( 'understrap-styles' );

	wp_dequeue_script( 'understrap-scripts' );
	wp_deregister_script( 'understrap-scripts' );

	// Removes the parent themes stylesheet and scripts from inc/enqueue.php
}
add_action( 'wp_enqueue_scripts', 'understrap_remove_scripts', 20 );

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {

	// Get the theme data
	$the_theme = wp_get_theme();
	wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.min.css', array(), $the_theme->get( 'Version' ) );
	wp_enqueue_script( 'jquery');
	wp_enqueue_script( 'popper-scripts', get_template_directory_uri() . '/js/popper.min.js', array(), false);
	wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/child-theme.min.js', array(), $the_theme->get( 'Version' ), true );
	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}
```
The code you sent doesn't have any indication of enqueuing jQuery at all.

**Comment by erinjohnson21** [comment]
I haven't upgraded the child theme, I don't think. It's version 0.3.1 that I have. 

I'll try the newer theme functions and see if that works. 

Thanks for the help!

**Comment by Thomas-A-Reinert** [comment]
You´ve been using an "Alpha"-Version of BootStrap4 which was not meant for production. Yes, I agree, the "UnderStrap"-Projekt should´ve pointed that out more clearly. But yes, that´s a fact and we can´t turn back the time.. Sorry for that though.

Anyway -  Alpha´s are subjects to change. Which did happen in your case. And due to the fact that you didn´t go through every **** iteration you seemingly lost/didn´t update stuff. As 0.6.7 for the parent and 0.3.1 for the child are really, _really_ old!

I´d say - sorry for that, that´s just my personal opinion, _not_ representative for the whole UnderStrap-Project! - But that´s your own fault for trying to build up a live site on development Code.

So what can you do? Check every freaking step/css-rule that goes wrong.

- Check for the navwalker class as @axlright recommended - that might solve your menu problems. But not your S/css styling. You gotta do that on your own in case you customized that.
- Check for any element that "misbehaves" - find out it´s class and check if it is still supported in BootStrap  final.

Really - I feel with you, because I did the same. I built up on an early alpha and now my really _heavily_ customized Theme plus WooCommerce is .. well.. "misbehaving".

Conclusion: Use Alpha´s for testing, NEVER EVER for PRODUCTION!
