### ISSUE TITLE
Using variables from the original _variables

### ISSUE THREAD

**Issue by digitaloutback** [understrap/understrap#673]
For example, I want to overwrite the `$body-color` variable to `$gray-700` but I'm getting:

`Error: Undefined variable: "$gray-700"`

What's the proper way to have access to these variables?

**Comment by axlright** [comment]
@digitaloutback In agreement with @ShariqKhan2012 

If you want to reference Bootstrap variables in your ` _theme_variables.scss` then you'll need to re-declare them above the line where you're referencing the variable. The other solution is to move your `@import "theme/custom-variables";` lower down (below `@import "assets/bootstrap4";`) in your `child-theme.scss` but this isn't recommended since you won't be able to change any of the default variables.

**Comment by ZacharyElkins** [comment]
@axlright wouldn’t it be possible to take the variables file import out of sass/assets/_bootstrap4.scss and put it into the main sass/theme.scss file?

Then you could load the variables before your variable overwrite file. As bootstrap variables have the default flag they will be overwritten either way.

**Comment by pattonwebz** [comment]
The variables.scss file can be included inside both the bootstrap stylesheet and the main site stylesheet before theme variables. I've done that in a different theme with no issues :)

You can also import the mixin file as well and use it inside of the theme stylesheet for making b additional button colors etc.

**Comment by Thomas-A-Reinert** [comment]
All above posted solutions from @ShariqKhan2012 , @axlright , @ZacharyElkins and @pattonwebz will resolve the issue. It´s up to you to decide which one suits you best. I´ll close this, because it ain´t an "issue" anymore, okay? Feel free to reopen if you have any remaining issues or post your experiences to this topic, okay?
