### ISSUE TITLE
Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by yamaks** [understrap/understrap#699]
## Issue is about..
  - [x] a Bug Report
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.6
  - **Woocommerce:** 3.2.6
  - **Language:** [  PHP 7 / Memory Size 256Mb ]

# Issue Overview for Bugreports

Hi, guys! 
Thank you for your excellent work. The second year I work with understrap. Help me understand why on a new project in some categories there is such an error:

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /home/macbook/2mac.com.ua/www/wp-includes/wp-db.php on line 1889

Only a few categories produce such an error. The rest open normally.

An error occurs even if a standard clean understrap theme is used.
When using Storefront Theme, no error is observed.

Here's the link to see: https://2mac.ua/katalog-tovarov/

Help solve this error.
Thanks!

**Comment by Thomas-A-Reinert** [comment]
Hi Yamaks,

would´ve been helpful to note that it seems to be a WooCommerce problem. But that´s just a sidenote ;)

I guess it´s pretty unlikely that this problem is UnderStrap related. Reasons are:

1. I got some client sites that have a few dozen categories that work like a charm.
2. Your categories themselves work like a charm too, e.g. https://2mac.ua/katalog-tovarov/tachpadu/

 It would be helpful if:
- You could raise mem to 512MB - TEMPORARY. Just for debugging purposes.
- Find out which template (and subtemplates/includes) is being used on that special page that throws the error.
  - For this a plugin like https://wordpress.org/plugins/show-current-template/ would be helpful
- Use https://wordpress.org/plugins/debug-bar/ and one of it´s plugins to find out what causes the ram consumption.

Please understand that we cannot help with the actual state of what we know. It´s just not reproducable for us and we don´t have enough information to start anywhere.

**Comment by ZacharyElkins** [comment]
I'm leaning on the side of this not being an Understrap issue. I have had no issues such as this on any WooCommerce sites I manage, but you who knows.

Usually this is a PHP version, plugin, or hosting issue. I would follow the suggestions @Thomas-A-Reinert  mentioned. If you have staging site I recommend disabling all other plugins except WooCommerce and checking. If the issue resolved then re-enable plugins one by one followed by checks. If you can provide further troubleshooting we may be able to help.

Also, 3.2.6 is an older version of WooCommerce. If all your other plugins are updated you should use the current version.

**Comment by yamaks** [comment]
Thank you, @Thomas-A-Reinert and @ZacharyElkins ! I will use your recommendations and report the results.

**Comment by yamaks** [comment]
@Thomas-A-Reinert  and @ZacharyElkins i followed your recommendations. The problem was solved by updating the Woocommerce
