### ISSUE TITLE
Have to re-save _child_theme.scss to see changes

### ISSUE THREAD

**Issue by brainchildguru** [understrap/understrap#714]
When I have gulp watch-bs running, I have to re-save the _child_theme.scss file to see changes almost every time I make a change. Does anyone know why this happens? How I can address it?

**Comment by axlright** [comment]
Thanks for reaching out @brainchildguru. Can you elaborate a bit on the expected behavior versus what you're experiencing? You say you have to re-save the _child_theme.scss file to see changes almost every time you make a change - what are you making a change to that you want to trigger `gulp watch-bs` that isn't working?

**Comment by axlright** [comment]
Hmmm. That's not the experience I have. Can you detail your local setup? Maybe others in the crew can give any helpful feedback.

**Comment by 0dp** [comment]
This sounds awfully alot like an issue we have had posted before. We used quite a lot of time debugging it but never found a solution because it was too localized.

@brainchildguru can you please fill out the issue template so we can see your setup

**Comment by Thomas-A-Reinert** [comment]
PLUS: this is child-theme related. Please open an issue in the child-theme repo. not in the main theme repo. thx in advance.
