### ISSUE TITLE
gulp-touch-cmd to set file modification timestamp

### ISSUE THREAD

**Issue by azharijelek** [understrap/understrap#718]
This is just an advice to use `gulp-touch-cmd` to set generated timestamp theme.css or theme.min.css. 

Because, from what I learned, our css files that generated by gulp aren't set with timestamp. So we need the help of `gulp-touch-cmd`.

Please note that I'm using **gulp4**, you may refer to #713 and this [reply](https://github.com/understrap/understrap/issues/645#issuecomment-381676942)

This is how I do it:

- `cd your_understrap_dir`
- `npm install --save-dev gulp-touch-cmd`
- in `gulpfile.js` please add: `var touch = require('gulp-touch-cmd');`
- still in `gulpfile.js` , inside function minifycss(){}, add .pipe(touch()) after .pipe( gulp.dest( paths.css ) )
- The function will look like this:
```javascript
// Minify CSS
function minifycss( done ) {
    gulp.src( paths.css + '/theme.css' )
        .pipe( sourcemaps.init( { loadMaps: true } ) )
        .pipe( cleanCSS( { compatibility: '*' } ) )
        .pipe( rename( { suffix: '.min' } ) )
        .pipe( sourcemaps.write( './' ) )
        .pipe( gulp.dest( paths.css ) )
        .pipe(touch())

        gulp.src( paths.css + '/custom-editor-style.css' )
        .pipe( sourcemaps.init( { loadMaps: true } ) )
        .pipe( cleanCSS( { compatibility: '*' } ) )
        .pipe( rename( { suffix: '.min' } ) )
        .pipe( sourcemaps.write( './' ) )
        .pipe( gulp.dest( paths.css ) )
        .pipe(touch());

    done();
};
```
- that's all

**Comment by 0dp** [comment]
Interesting.

I would like to see if others can 'replicate' the scenario here. FWIW my files are stamped correctly 👍

**Comment by Thomas-A-Reinert** [comment]
Files get correct timestamps on win10.

**Comment by holger1411** [comment]
Closing this because it was solved or isn´t a problem anymore

**Comment by WilliamStam** [comment]
linux mint 19.1 (or ubuntu bionic 18.04)

i know this is old'ish and im not using your project but i just had this issue with gulp sass and it drove me up the walls.

basically my project copies the css file to an asset folder and uses the path + mtime for a hash, the problem was that the generated css file's "modify" timestamp inherits the modify time from the parent file but not any of the @imports 

`style.scss` compiles to `style.css`

`style.scss` has the contents of:

```
@import "variables";
body {
  background: $body-bg;
}
```

changing the `$body-bg` in variables generates a new `style.css` file with the modify time still belonging to `style.scss`. 

so i end up with something like this:

```
$ stat style.css 
  File: style.css
  Size: 31        	Blocks: 8          IO Block: 4096   regular file
Device: 807h/2055d	Inode: 8519973     Links: 1
Access: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Access: 2019-02-14 14:45:31.497671082 +0200
Modify: 2019-02-14 14:37:38.577000000 +0200
Change: 2019-02-14 14:45:31.453670599 +0200

```

notice the modify timestamp being different from the other 2


-----
>Closing this because it was solved or isn´t a problem anymore 

its still a problem. but seems that its a gulp 4 issue. not too impressed that i need to load a node library JUST to update the modify timestamp of a file on editing. but yes, this sint a problem with your project its a problem with gulp4.

**Comment by 0dp** [comment]
OP is right. Googling the issue revealed
> It's a feature.

IMO it's a bug

**Comment by 0dp** [comment]
https://github.com/gulpjs/gulp/issues/1461

**Comment by NathanBowers** [comment]
Thanks to everyone on this thread. I thought I was going crazy after upgrading to Gulp 4.

Using `gulp-touch-cmd` solved my all-day-killing problem of BrowserSync not refreshing the CSS when saving Sass partials.

**Comment by Thomas-A-Reinert** [comment]
Thumbs up! I assume this problem got solved
