### ISSUE TITLE
No conflict with jQuery 1.12 and Bootstrap 4?

### ISSUE THREAD

**Issue by kmob2** [understrap/understrap#739]
Hello,

I was wondering if you're not running into any jQuery/Bootstrap conflict issues.

WordPress core supplies jQuery 1.12.x and it's not recommended to upgrade to 3.x as it might break plugins. However Bootstrap 4.1 requires jQuery 3.3.x.

When I look at your understrap demo site, I see you're only loading jQuery 1.12 from WP core, but also running Bootstrap 4.1.

Are you not experiencing any issues running Bootstrap 4.1 with jQuery 1.12?

Edit: Reading the bootstrap javascript docs at https://getbootstrap.com/docs/4.1/getting-started/javascript/ they recommend jQuery 3.x however they refer to https://github.com/twbs/bootstrap/blob/v4.1.1/package.json for dependency check. From what I can see there, it seems bootstrap 4.1.1 works with jQuery 1.9.1 - 3

Just double checking. You can confirm that as well, right? No known issues with Bootstrap 4.1 and jQuery 1.12.x ?

**Comment by pattonwebz** [comment]
I'm not aware of any specific known issues with running the older version of jQuery that WP bundles.

IIRC in the past I was part of a conversation on the Bootstrap github issue about the min version bump and it was detailed the higher version recommendation is based purely on browser compatibility (the browsers that Bootstrap supports all support a 3+ version of jQuery) and not a recommendation based on feature set of the dependency (since Bootstrap will work with jQuery with featuresets as far back as 1.9.1).

**Comment by holger1411** [comment]
The Bootstrap team decide to support the WP jQuery version, too.
There was an ongoing discussion there, but at the end they re-add jQuery suport down to the 1.12 version.
The result (without this) would be that no WordPress theme could use Bootstrap anymore without problem´s or without loading different versions of jQuery. 

So yes, I confirm that there are no known issues. And if so it would be flagged as bug and will be fixed by the BS team

**Comment by kanlukasz** [comment]
After more than two years since this thread, I would like to ask, is the situation still the same?

**Comment by IanDelMar** [comment]
> After more than two years since this thread, I would like to ask, is the situation still the same?

Yes.
```
"peerDependencies": {
    "jquery": "1.9.1 - 3",
    "popper.js": "^1.16.1"
},
```
https://github.com/twbs/bootstrap/blob/a716fb03f965dc0846df479e14388b1b4b93d7ce/package.json#L108
