### ISSUE TITLE
Gulp error: Task 'default' is not in your gulpfile

### ISSUE THREAD

**Issue by aaronrobb** [understrap/understrap#800]
Getting an error when running Gulp on a new install with the latest understrap installed.

Gulp is installed.

When i run gulp, it says 
[16:40:36] Using gulpfile ~/workspace/wp-content/themes/circles2018/gulpfile.js
[16:40:36] Task 'default' is not in your gulpfile
[16:40:36] Please check the documentation for proper gulpfile formatting

I checked the gulp file and there is no 'default' command in there.

**Comment by SalmanPK** [comment]
Not having a "default" command is not a bug. Run one of the available commands, or feel free to add "default" commands to your liking.

**Comment by holger1411** [comment]
We just defined no default.
Because there is no default task which everyone needs to do again and again, because it depends on how and for what you use the theme.
So if there is a default task you need again and again for your specific workflow, define it as default.
If not, use just the definded tasks
