### ISSUE TITLE
Homepage content hidden in mobile view

### ISSUE THREAD

**Issue by clarkewd** [understrap/understrap#841]
When viewed on iPhone most of the [homepage](https://understrap.com/) text, "The Bootstrap 4 + WordPress Theme Framework" is hidden:

![screen region 2018-11-02 at 11 08 24](https://user-images.githubusercontent.com/156377/47923411-bb5e2900-de8f-11e8-8b9e-686ee291779e.png)

**Comment by clarkewd** [comment]
well, it's still broken.

**Comment by pattonwebz** [comment]
I see this same behaviour on the site as well. The menu has no small screen sized wrap so it just overlays the page opening contents.

The issue isn't an issue directly related to the theme so I think that is why the issue was closed here. But it is still an issue with the site - I just don't think there is a repo for that site. 

@holger1411 you may be interested in this so pinging you.

**Comment by Thomas-A-Reinert** [comment]
Well, sorry for closing this without any comment. I can confirm that this is not only an iPhone issue, but a mobile related / conceptional issue in general.

As William already said, we (the UnderStrap contributors) have no access to Holgers site.
