### ISSUE TITLE
Use OOP (Object Orientated) design patterns / classes

### ISSUE THREAD

**Issue by raisonon** [understrap/understrap#844]
## Issue is about..
  - [x ] a Feature Request
  - [x ] a Suggestion

Hi, I've rebuilt the functions.php to call a classes so we can manage the functions in the theme in a more structured way according to best practice.

Is there any interest for me to share this or is there a particular reason this has not been adopted already?

Using classes is much more scalable when building more complex functionality within the understrap theme.

Thanks

**Comment by pattonwebz** [comment]
I like the idea of moving to a class based invocation for themes. I think it's the way forward :)

**Comment by 0dp** [comment]
I think you should share your fork/gist/code here so it can be openly discussed.

**Comment by raisonon** [comment]
Hi @0dp , here is how I have structured it for the child theme: https://github.com/understrap/understrap-child/compare/master...raisonon:fork/classes

I added an auto-loader so that it's easy to add new classes.

Would need a bit more effort to do the same for the understrap main, but not too much. Same principles..

**Comment by 0dp** [comment]
Great @raisonon,
Of cause the decision is ultimately @holger1411 s to make.
But this could work as a starting point for such a transition. Given that it would be best practice to covert the entire project where it applies.

**Comment by AlchemyUnited** [comment]
@raisonon - Points for the idea! But I'm not so sure you've nailed the execution :) Let me try to explain (quickly), off the top of my head. 

- The hooks (i.e., the when) should be separated from the what (i.e., method)
- Use arrays for hooks. 
- Use arrays for enqueue'ing (because they can be filtered, if necessary)

Here a couple examples (that I think I've since updated but haven't pushed (for some reason). 

- https://gitlab.com/WPezLabs/wpez-theme-child-basic/blob/master/App/Setup/ClassSetup.php

- https://gitlab.com/WPezLabs/wpez-theme-child-basic/blob/master/App/Core/HooksRegister/ClassHooksRegister.php

Ultimately, at some point (in the near future?), the setup is going to be a container or will use a container. The idea being, the classes should only need to be "configured". Actually new coding is minimal since the classess handle all the repetitive heavy lifting, all you do is set / load the data / settting they need. 

Something like that ;)

**Comment by raisonon** [comment]
I really like that, thanks for the examples. 

I guess the problem with that is it abstracts from the well known functional approach a lot, but i do like how you have the original functional approach in the comment above to show what's going on.

eg.

`        // add_filter( 'image_size_names_choose', [ $new_images, 'imageSizeNamesChooseFilter' ], 100, 1 );
        $this->_arr_filters[] = [

            'active'    => true, //   <<<
            'hook'      => 'image_size_names_choose',
            'component' => $new_images,
            'callback'  => 'imageSizeNamesChooseFilter',
            'priority'  => 100
        ];
`

**Comment by pattonwebz** [comment]
Subsystems that act as loaders, like @AlchemyUnited shared in the 2nd gist, are becoming increasingly common - for filters but even more commonly seen when used as script loaders. There's not a particularly common design pattern for their implementation though. Have a look at some other examples to find which one suits your use case best. Many of them are somewhat opinionated about how to use them so not all of them fit all needs.

**Comment by AlchemyUnited** [comment]
@raisonon said "...the problem with that is it abstracts from the well known functional approach a lot..."

Well. Um. Yes, it abstracts. No that's not a / the problem. It's The (Best?) Solution for moving the beast forward :)  << Note: The :) Please don't misread. I'm being "funny" and not a typical dev-d*ck. 

Once you move from hardcoding everything to arrays (whenever possible) things - imho - actually get A LOT easier. Easier to do, and more importantly, easier to learn. From styles and scrirpts to CPTs, there's a A LOT (read: too much) coding that could / should be closer to configuring (i.e., defining the various args via arrays / objects). 

In my mind, once I get some time, I'm going to end up with a config container that'll hold all the basics (e.g., custom taxonomies, custom CPTs, etc.). Ideally ZERO coding. Something I could give to a jr. dev and they'd have to work REALLY HARD to muck it up. 

I have some other examples if y'all are interested. I actually also have an OOP / MVC theme framework that once it gets some love is more of less the same idea. Mostly (if not all) re-usable modules configured and stitched together in order to "custom build" each project. 

Note: There will also be new and completely custom work. I get that. But when I see (e.g.,) script / style enqueue'ing ton a bunch of different way, I cringe. And usually swear. LOL.

**Comment by AlchemyUnited** [comment]
p.s. Again, I want to be clear. I'm only trying to help. I agree, these are "extreme" - if not odd in the World of WordPress - ideas. But I've been to this rodeo a couple of time. I've broken things down, and yes abstracted ;) In my eyes / mind, nearly everything is an "object". It's defined. We should be configuring such things not coding them. 

imho, of course ;)

p.s. Since I have you attention, this is something (I'm proud of) and sense y'all will appreciate:

https://gitlab.com/wpezsuite/WPezAPI/WPezAPI

The read me, needs to be updated but you get the general idea. That is, to put a facade (?) in from of all the WP sprawl and confusion. It's 95% done. I think :) What I'm wanting to do at this point is is IoC of DI for the "child classes" and not do the actual instantiation in the parent. 

I've been reading up on containers, etc. but haven't had a moment to implement. If y'all have any thoughts on how to push this over the finish line, please share. 

tia -
mark

**Comment by LukaszJaro** [comment]
A very good example of going from functional to OOP is this new popular advanced starter theme: [](https://github.com/wprig/wprig)

Compare v1 to v2, different beast, for non OOP users v2 looks very different and complicated from my POV.

**Comment by AlchemyUnited** [comment]
@LukaszJaro - Thanks for sharing that. Perhaps I didn't dig deep enough, but I poked around this 

https://github.com/wprig/wprig/tree/v2.0-alpha 

and didn't really recognize anything that was OOP-y. What did I miss? 

In my (ideal) mind, going to OOP for themes (or plugins) would likely also mean adopting some sort of MVC mindset. That is, models and views are often reusable standard components (read: classes) with the controllers being the unique bits that stitch those together. 

The biggest head-scratcher for WP theme dev (for me) is nearly all of them are doing the same thing in some slightly different - but hardly unique - way. Sure the CSS might be different but the basic structure / layout / functionality is the same. How many ways can we code a footer with three widget areas in it? The current answer is: Too many. 

This is also inefficient in that each new iteration / version / reinvention of some component (or model) needs to be tested, etc.  80% of 80% of WP themes are the same. The ultimately goal could be to reduce the time wasted on reinventing the wheel and shift that saving to the 20% that's bespoke. 

imho, of course ;)

**Comment by LukaszJaro** [comment]
@AlchemyUnited, I was looking at this https://github.com/wprig/wprig/tree/v2.0
But you are right, I looked over it quickly and saw classes, namespaces, automatically assumed OOP..
Disregard above, I jumped ship to quickly.

**Comment by AlchemyUnited** [comment]
@LukaszJaro  - No problem :)

I hear ya tho. OOP does take some adjustments and it takes a while. That said, to me, it's worth it. You think better, architect better and ideally code better when you're tying to OOP. In a eco-system like WP there's a A LOT of redundancy that could be reduce if more ppl embraced OOP. 

For example, and not to get off topic but this is a plugin I'm working on. 

https://gitlab.com/WPezPlugins/wpez-widgets-demo

What's cool, or what I think is cool, is how the fields are done. Long to short, it's not every dev doing some version of a (e.g., text input). Instead, there's now a standard (widget) text input that can likely be used 90% of the time. Done! Just configure it and move on.  :)

**Comment by raisonon** [comment]
For MVC WP there is:

https://github.com/raisonon/prodpress (which I am involved with)
https://github.com/themosis/

I think a theme with a clear way of creating components and reusable elements with MVC would be great. Perhaps this is a new project outside of Understrap though...

**Comment by AlchemyUnited** [comment]
@raisonon thanks for sharing. Themosis is kinda close but for me not what I have in mind. I think something that embraces Atomic Design / (React) components would be ideal. And doable. 

re: "Perhaps this is a new project outside of Understrap though..."

That might be my fault, sorry. But you started it :) I was only saying I like the idea and have a POC that I could share (once I get some time to refine it a bit more).

**Comment by pattonwebz** [comment]
In my time on the .org theme review team I have v seen many themes start moving towards an OOP approach. To be honest I haven't seen a theme truly do it and to be fair I don't think the necessary structure is available in WP for actually making it Hayek. Particularly the way that WordPress templating system works means that any OOP theme usually ends up needing to write their own template/views engine (a lot use Timber/Twig I've seen).

**Comment by pattonwebz** [comment]
@AlchemyUnited The views/partials is actually the very crux of the issue that I see here and why I feel that it's not exactly workable with WordPress. 

For themes outside of the .org directory this is not at all an issue but for themes in the directory they are required to use core features that already exist instead of rolling their own variants. Essentially they must use the core template engine and not reinvent it or override the main parts of it so that it works differently than expected (cross compatibility is a big concern for us on the team).

One theme that I have been keeping an eye on is https://github.com/justintadlock/mythic. Justin is a long standing member of Theme Review Team and has a lot of knowledge and influence in the theme development world. He has been exploring the limits of what is and is not allowable in a them for the .org directory.

Again worth mentioning that my thoughts shared here come from the point of view of themes for the .org directory. Themes which are not in the directory do not need to concern themselves with things like using core features first, compatibility with existing plugins or data portability between themes.

**Comment by pattonwebz** [comment]
Another side note is that headless WP is a thing which works great with a standalone React frontend (completely unrelated to themes but headless + react is becoming increasingly common and worth mentioning here I think).

**Comment by bacoords** [comment]
Thought I'd add a few random thoughts here:

- I agree that we'd need to set up the parent theme and not just the child theme. It would be interesting to see a fork of that as well, but I imagine it'll be a huge undertaking...
- Most of WP really isn't written this way (for better or worse), so I don't see it as a super-high priority item. I understand that it's better, but that doesn't mean it's necessary or right for this project.
- I think that by moving to OOP here, we raise the barrier of entry for newer devs learning how to jump into the wonderful world of messing around with themes. There's a lot of great themes at that level (like ones mentioned above in this thread), but I'm not sure it needs to be here as well.

My vote ultimately is to close this issue, but if there's a ton of interest in moving in this direction, I'm not against it.

**Comment by pattonwebz** [comment]
I wouldn't be opposed to closing this. I do think that the use of classes for themes is the way forward but the majority of the themes ecosystem isn't built that way so I may be on the minority side of the argument. It also creates a spaghetti and meatballs type situation lol

Building a theme that takes advantage of OOP concepts would likely be best handled in a fresh build anyways.

And I do agree that moving to OOP can be considered a complexity that isn't needed (but in my mind highly desirable for PHP overall).

**Comment by raisonon** [comment]
Sure, left WPland because it never progressed past this argument so close if you fancy.

Done right you could show how much easier separation of concerns makes building but agree it will be against consensus.

Not my fight any more - close if u fancy.

**Comment by AlchemyUnited** [comment]
@bacoords said "I think that by moving to OOP here, we raise the barrier of entry for newer devs learning how to jump into the wonderful world of messing around with themes."

Yes. But that's kinda the point here.

1) There are TONS of projects / themes already appealing to those devs. And then once they "grow up", then what? 

2) Plenty of those theme only teach and / or enable bad habits. Habits that say a Laravel dev would gringe at. Ultimately, an OOP based theme that focused more on DRY and configuring" and less on "learn the WordPress way" would be easier to learn for beginners. There is simply too much unnecessary noise in traditional WP dev that it hurts. It doesn't have to be this way. 

@raisonon - Yup. I hear ya bother. I hear ya,

**Comment by pattonwebz** [comment]
> There are TONS of projects / themes already appealing to those devs. And then once they "grow up", then what?

There are other options for Themes too that take a more OOP approach. Check out WP Rig if you're looking for something like that. Also check out SAGE/Roots if you wanted to experiment with an alternative templating engine than what core offers. This also is maybe of interest to you: https://github.com/outlandishideas/oowp

**Comment by danemorgan** [comment]
I'm definitely a functional coder. I've never really had occasion to find the benefits people claim for OOP. I would vote for closing this, but I would jump in and try to figure out how OOP works within a WordPress theme if that's the way the community wants to go.

It strikes me that more than converting Understrap to OOP, a fork of it, or even a clean slate like "Oopstrap", separate from the main project to explore that possibility as a sister theme might be more appropriate. It sounds, from the conversation so far, like there is a lot of discussion between where we are and where a workable OOP version of Understrap would be.

**Comment by pattonwebz** [comment]
I do think a fresh fork or partner theme is the best course of action to go full-on OOP for a theme. Slowly iterating it in would be a very long process in my mind.

I am also of the opinion that if OOP brings complexity that outweighs the benefits it isn't worth it. It is hard to find the value to the end-user of building a theme with OOP. It basically makes zero difference to an end-user what the code is made from so long as the code works and is bug-free. The benefit to the developers though can be significant.

There are more standards built around OOP styles. PSRs for example https://www.php-fig.org/. At a very entry-level PSR-4 is a big simplification from developmental standpoints. Autoloading files and removing any decision paralysis of where the file should be placed and what it should be named is always a huge benefit to me when building things.

**Comment by danemorgan** [comment]
> It is hard to find the value to the end-user of building a theme with OOP.

How does this change when we consider that the target audience for Understrap has been stated to be developers, not end-users?

Not that we are obligated to continue to that end, but I think it is true and that it colors some of these kinds of decisions because the people we are doing this for are supposed to care about the code behind it at least a little.

**Comment by danemorgan** [comment]
I'm closing this for now. If we revisit, I think we should do so as a sister project and plan on a long iterative process with deep discussions along the way.
