### ISSUE TITLE
Usable Javascript calculator for cart

### ISSUE THREAD

**Issue by flaagma** [understrap/understrap#863]
Hi,
I want to create script calculator that simply calculate the price automatically refresh when buyer input quantity.

Here the layout of calc [https://ibb.co/DQLFzJM](url)

I was try but always failure
Thank you

what is the best way to create a javascript calculator?

## Issue is about...

  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | Javascript ]

---

 * Test

**Comment by Thomas-A-Reinert** [comment]
I'm sorry to say but this is not something that affects understrap or a problem caused by understrap but more a generic Javascript question. I'd recommend https://medium.freecodecamp.org/how-to-build-an-html-calculator-app-from-scratch-using-javascript-4454b8714b98 for example. Or just head over to https://stackoverflow.com/questions/tagged/javascript

Good luck.

**Comment by flaagma** [comment]
Oh thank you very much
