### ISSUE TITLE
Unable to minify JavaScript when Template Literals are added to custom-javascript.js

### ISSUE THREAD

**Issue by blachawk** [understrap/understrap#866]
- [ ] a Bug Report

## Please tell us about your environment:
  - **WordPress Version:** 5.0
  - **OS Version:** [Windows 10]
  - **Browser:** [ all ]
  - **Language:** [ Javascript]
---

# Issue Overview for Bugreports
In the event we want to add our own custom JavaScript to UnderStrap, instructions are given in the package to create a file called custom-javascript.js.  This process works.  But if we add JavaScript **[template literals](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings)** to the code in that file, UnderStrap fails to minify, and the developer is kicked out of **gulp watch-bs**.  

* Example of what to add:
> var mTempLit = `` ` ``compile`` ` ``;

**Comment by Thomas-A-Reinert** [comment]
Hi. UnderStrap currently only supports "vanilla js", no es6 or ts which you're trying to use..

**Comment by blachawk** [comment]
Thanks for the quick feedback.  @Thomas-A-Reinert  can you add this in as a feature request sense template literals (or template strings in ES5) are a native part of the JavaScript core language.

**Comment by Thomas-A-Reinert** [comment]
Hi Kensley. No problem at all.
My suggestion for a quick-fix would be to create a folder like js-src and run any es6/ts compiler over it that compiles vanilla-js into the js folder which will get concatenated. Or just compile it as custom-javascript.js which will then (probably, sorry I´m not really busy with US atm, so I can´t really tell) get processed (minified/concatenated) through the gulp-workflow.

As js-src is a folder unknown to UnderStrap and its Gulp workflow it will never be touched. That should save your source-files. You may extend gulp with some babel-transpiling or transpile it with a desktop-app.

Personally i´ve never been a javascript-evangalist (honestly, i HATED JS), but due to my current job, I need to get around with es6/ts. As i´m currently taking on some WP-projects besides my daily job i´m really eager to get that es6/ts-thingie working too. So that´s on my todo list anyway. Can´t/Won´t promise anything anytime nearby though - that´s why I gave advice for some workaround.

In case you get that to work on your own (gulp-workflow) we´d be happy to share your commit.

**Comment by blachawk** [comment]
Many many thanks for the tips and info.  It definitely gives me something to work with.

**Comment by 0dp** [comment]
#613

**Comment by 0dp** [comment]
#862

**Comment by 0dp** [comment]
I've referenced two other issues that touch base with your request and you.might find some more info to help you on your way

**Comment by blachawk** [comment]
I just want you guys to know I really appriciate your care and effort in making a solid product with the very little time you have.  Just for clarity purposes,  the main issue I see in this is allowing the use of back ticks for strings.  [More on that here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).  This really has nothing to do with ES6 or ts (TypeScript). Its been a core part of the language in forming JavaScript strings.  

I'll be diving into some creative workarounds this week (thanks to you guys) and see what I come up with. Appreciate any through or planning in considering this for any future releases of UnderStrap.

**Comment by 0dp** [comment]
Do you get any errors in the terminal and/or in the browser console?

**Comment by blachawk** [comment]
The error occurs when I'm either about to run **gulp watch-bs**, or if I am already running it and **save** my work.  Below is the error I get in visual studio code...

```
events.js:183
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\gulp-uglify\lib\create-error.js:6:14)
    at apply (c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\lodash\_apply.js:16:25)
    at wrapper (c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\lodash\_createCurry.js:41:12)
    at c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\gulp-uglify\lib\minify.js:55:15
    at DestroyableTransform._transform (c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\gulp-uglify\composer.js:12:19)
    at DestroyableTransform.Transform._read (c:\Users\...\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (c:\Users\lewisk\...\wp-content\themes\understrap\node_modules\readable-stream\lib\_stream_writable.js:334:11)
```

The moment I remove... 
```
 var tempLit = `hello world`;
```
from my custom-javascript.js file, **gulp watch-bs** works correctly again.

**Comment by 0dp** [comment]
A quick read up on what you are after.
gulp-uglify does not support ES6 aka ES2015 specifications.

from MDN
```
Template literals are string literals allowing embedded expressions. You can use multi-line strings and string interpolation features with them. They were called "template strings" in prior editions of the ES2015 specification.
```

https://github.com/mishoo/UglifyJS2/issues/950
```
...The releases do not include ES6 support.
```

For ES6 support you need `https://www.npmjs.com/package/gulp-uglify-es` instead of the current.
But you'll need a few other components as mentioned in #613 like gulp-babel.

If you'd like to try and work on it and contribute I would suggest you post your PR to the gulp4 branch where a lot of new cool features will be worked on soon.

**Comment by hartwm** [comment]
`npm install @babel/core --save-dev`
`npm install gulp-babel --save`

In gulpfile.js require babel
`var babel = require('gulp-babel');`

Find gulp scripts task and add 

` .pipe(babel({
      presets: ['es2015']
    }))`

Here is example: 
```
// Run:
// gulp scripts.
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
  var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.bundle.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',

        // Adding currently empty javascript file to add on for your own themes´ customizations
        // Please add any customizations to this .js file only!
        paths.dev + '/js/custom-javascript.js'
    ];
  gulp.src(scripts)
    .pipe(babel({
      presets: ['es2015']
    }))
    .pipe(concat('theme.min.js'))
    .pipe(uglify())
    .pipe(gulp.dest(paths.js));

  gulp.src(scripts)
    .pipe(concat('theme.js'))
    .pipe(gulp.dest(paths.js));
});
```

**Comment by 0dp** [comment]
Hi @blachawk there is a new gulp4 PR #883 that has es6 support that needs testing

**Comment by Thomas-A-Reinert** [comment]
According to my tests, this should work out fine. How about you @blachawk ? 
As this issue is now more than half a year stale, I´ll be  closing it.

Feel free to reopen, if the problem persists!

**Comment by elshaddae** [comment]
Looks like 883 was never merged, is uglify-es the final alternative to allow string literals?

**Comment by 0dp** [comment]
> Looks like 883 was never merged, is uglify-es the final alternative to allow string literals?

Correct, it was never merged. instead a different PR was merged, but i have no idea of the state of it 😞
