### ISSUE TITLE
Translation: understrap-child not all translated in inc/template-tags.php

### ISSUE THREAD

**Issue by SvaSanRA** [understrap/understrap#893]
## Issue is about..
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.0.3
  - **OS Version:** [Windows 10] | Linux [Linux Mint 19.1 Tessa]
  - **Browser:** [ Chrome XX | Firefox XX | IE XX | Mobile Chrome XX ]

Hello Hologer. I liked your starting theme Understrap and I decided to use it in my project. While the project is being created for a Russian-speaking audience, but in the future I plan to make it in English. After installing the child theme Understrap, in my case the translations into Russian did not work completely, such as “Posted on”, “by”, “Posted in”, although there is a translation in the ru_RU.PO file. I started to figure it out and found out that something is not correctly working out substituting the macro for the phrases injected into the function esc_html_x () and esc_html __ () thet are in the file inc/template-tags.php. When I change a line:
`esc_html_x ('Posted on', 'post date', 'understrap');`
on
`esc_html_x ('Posted on% s', 'post date', 'understrap');`

The translation occurs, but the macro "% s" falls into the translated word.

The only way out for me is to substitute the translated words directly into functions, but this is not the correct approach.
Please tell me what could be the reason for this behavior of built-in functions. Perhaps the problem is just me and she on the surface.

---

Thank you in advance.

**Comment by Anzan** [comment]
I'm using Understrap for a french theme and some translatable strings in the theme are out of sync with the `PO` file: `"Posted on %s"` is now `"Posted on"`, `"by %s"` is now `"by"`. It's simple to just add a new string in the `.PO` file for the new strong content and save it as `.MO` with Poedit but someone should update the language files that are provided.

**Comment by Thomas-A-Reinert** [comment]
Sorry, but call me stupid - I´m not really getting the problem.  Could you please clarify?

**Comment by Anzan** [comment]
When making a theme in another language than english, you realize some Understrap strings are still in english when you switch language, even with all the `PO/MO` files in `/languages/,` I think some people have made changes to strings without updating the `PO` files that contain the translation in other languages. For example, see this commit:

https://github.com/understrap/understrap/commit/b6af4ac4528fd65c5002d47e1c142fffdd94b326#diff-5915276465e785d5f7897d71685fca5f

`'Tagged %1$s'` was changed to `'Tagged %s'`, but the language `PO` file that associates the translation with `'Tagged %1$s'` was not updated to `'Tagged %s'`, so now that translation is lost, and a theme in french (in my case) that should be translated to, say, `Taggé %s`, is still in english instead, because it contains a translation for `'Tagged %1$s'`, an orphan string not found in the theme files anymore.

**Comment by danemorgan** [comment]
I have never worked with internationalization.

Can anyone explain why the change was made from 'Tagged %1$s' to 'Tagged %s' in this specific location. There is a lot of '%1$s' still through the PHP in the theme. Why does this one change but not the others?

Is the solution here to modify the .po and .mo files to match the new PHP, or is it to modify the PHP back to what it was?

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
