### ISSUE TITLE
What happened to `understrap_slbd_count_widgets`?

### ISSUE THREAD

**Issue by swinggraphics** [understrap/understrap#900]
Hi. I'm trying to understand what happened to `understrap_slbd_count_widgets` and what to use as the replacement. I see the function was removed as part of a pull request to solve an issue for Polylang, but it was removed abruptly, without deprecation. Consequently, my child theme broke after updating from 0.8.8 to 0.8.9.

**Comment by swinggraphics** [comment]
@alexbogias Not the case. Just to reiterate, `understrap_slbd_count_widgets` was [completely removed in 0.8.9](https://github.com/understrap/understrap/commit/05cbe7bedf4aab0559bbf2ee634a88eb06d397d9#diff-fbd704194353a2019b0fb7f93d18188e). The reason my child theme broke was because it called `understrap_slbd_count_widgets()`, which of course errors as an undefined function.

**Comment by IanDelMar** [comment]
It was removed because of its incompatibility with the `widget_display_callback` hook which affected e.g. the plugin Polylang (see #796 and #852). It would have been better to keep the function as deprecated - my fault. The quickest fix is to put the old `understrap_slbd_count_widgets()` into your child theme's `functions.php`.

**Comment by swinggraphics** [comment]
Yes, copying into my child's functions.php was what I did. Just checking it really should be gone. ;) Cheers.
