### ISSUE TITLE
Best practices for updating your staging and live sites through Git? 

### ISSUE THREAD

**Issue by ramojej** [understrap/understrap#909]
I'm currently using Understrap Child. My practice is whenever I update something in my local machine, I need to run the Duplicator plugin (exclude node_modules), upload it in either the test or the live site. This is getting very tedious and repetitive.  Any advice on how you guys update your sites using Git? Thanks!

**Comment by 0dp** [comment]
A simple setup is creating a private repo for your theme and push your local changes to the repo. Then on staging and live you can clone the repo, and from there on you can do a simple pull on staging and live; Everytime you pushed changes from local.

**Comment by axlright** [comment]
I use WP Engine for managed hosting. We have ~30 installs there. WP Engine allows for direct git push deployment, so it takes a few keystrokes to push to either production / live or staging. Super duper easy!

**Comment by ramojej** [comment]
Thank you, 0dp and axlright. But what if the client provided the hosting? So direct git push will be dependent on the account/hosting the client bought?

**Comment by 0dp** [comment]
If you can use git on the clients hosting, then pulling the changes should be straight forward.

If not I guess you are stuck with ftp

**Comment by pattonwebz** [comment]
When git is not available on the clients host in the past I setup git hooks to do the deploy over FTP when I pushed or committed to certain branches. You can set it up to be triggered by webhooks or local git hooks depending on your needs. It has been a long time since I've used scripts to do this but I remember it was not super difficult to figure out (even with me having zero expertise with git hooks at that time).

**Comment by axlright** [comment]
Yeah I have done this as well. I have some post-deploy webhooks I could dig up that I've installed on a Dreamhost server to deploy to a remote server after a git push. A lot is dependent on how the client server is set up. If I recall, Beanstalk does a form of automated post-deploy webhooks via ftp?

**Comment by pattonwebz** [comment]
I have not used Beanstalk myself but it does have some deploy systems I believe. I have had the luxury to use deploybot through a gitlab integration before and it was pretty awesome. Could handle mostly any kind of deploy method we needed and was super easy to configure for each project.

I don't think there is any one perfect solution to doing deployments with code versioning.

**Comment by xicubed** [comment]
Started using GitLab CI/CD – when I push my local changes get pushed to gitlab, git checked out via and onto the runner, and rsynced from there to staging. Use WP-CLI to generate a new wp-config.php with variables stored in GitLab and relevant to the correct stage. Can use WP-CLI for db imports/exports/url substitutions as necessary. Instead of going from localhost to staging I get a fresh copy of staging including the database (in case someone's added something...) then push it back through.
