### ISSUE TITLE
Can't add/overwrite a breakpoint

### ISSUE THREAD

**Issue by ramojej** [understrap/understrap#918]
I'm using the child theme. I tried adding a new breakpoint in "../../src/sass/boostrap4/variables"

```
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px,
  xxl: 1366px
) !default;
```
Also tried to overwrite it by adding the same code in _child_theme.scss, but it's not working.

**Comment by 0dp** [comment]
try adding it to `_child_theme_variables.scss` instead and remove the `!default`

**Comment by ramojej** [comment]
Done. And still not working.

```
@import "theme/child_theme_variables";  // <--------- Add your variables into this file. Also add variables to overwrite Bootstrap variables here
@import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Change from /bootstrap3 to /bootstrap4 Watch out! just for testing in the moment!

```
Should the bootstrap4 go first then the child_theme_variables?

**Comment by 0dp** [comment]
No, it should not go first.
Have you checked your compiled css, if your breakpoint is available one way or another?

**Comment by ramojej** [comment]
It's in the compiled css! However when I use 

```
@include media-breakpoint-between(xl, xxl) {
                    right: auto;
                    left: 50px;
                }
```

It's being only compiled to  @media (min-width: 1200px) {}, when it should be @media (min-width: 1200px) and (max-width: 1366pxpx) { ... }

**Comment by 0dp** [comment]
hmm strange

**Comment by ramojej** [comment]
Guess I'm not going to use SASS for this part in the meantime.

**Comment by ramojej** [comment]
> hmm strange

Did you try to replicate the error? I can't really make it work.

**Comment by pattonwebz** [comment]
@ramojej the mixin that generates the CSS here works in a not-so-intuitive way. Could you try this and let me know if it results in the CSS you need:

    @include media-breakpoint-between(xl, xxl) {
        right: auto;
        left: 50px;
    }

**Comment by ramojej** [comment]
@pattonwebz It worked! ... but why? can you please explain how did it happen? Does it have something to do with the naming of the breakpoints (xl, xxl, xxxl)? Thanks!

**Comment by pattonwebz** [comment]
@ramojej I am glad this worked for you. I too have been hit by this same problem before because I feel like the `media-breakpoint-between()` mixin is setup in a not-so-friendly way.

What confuses me about this is where they get their integer values is not consistent between the parameters passed. The first parameter it wants is the min value which works as I expected because it takes the integer from the min value of the stated breakpoint. The 2nd paramiter though is the max value and it flips and takes the integer for this one from the MAX VALUE OF A BREAKPOINT.

What you expected (and also what I expected as well first time I used this) is that the 2nd parameter would accept the value from the NEXT breakpoint after the one we want. Instead it expects the name of the breakpoint WE NEED TO BE INSIDE.

I agree that it's confusing it works this way but that's how they made it work.

**Comment by ramojej** [comment]
@pattonwebz it's so confusing. I guess I'm not going to use SASS for this part. Thanks!

**Comment by Thomas-A-Reinert** [comment]
Child theme related. Please refer to the Child theme issue tracker. THIS is not the right place to raise this issue. Closing it therefore. 

https://github.com/understrap/understrap-child

**Comment by Thomas-A-Reinert** [comment]
BTW: As this issue may raise again and again with new Child-Theme users... Would anyone please be so king to raise it again the CHILD-THEME issue tracker and provide the solution? Just a wish..
