### ISSUE TITLE
Loading style and scrips after HTML is render

### ISSUE THREAD

**Issue by BohemiansThemes** [understrap/understrap#934]
Is there a chance to improve theme loading speed? 

How should I set styles and scripts to load after HTML is render?

**Comment by axlright** [comment]
I think this needs to be done on a case by case basis. 

We use a combination of CriticalCSS to load critical styles for above-the-fold content into the `<head>` then defer the main stylesheet to be loaded after the critical path elements are rendered. We use UnCSS to remove all styles from the compiled stylesheets which aren't being used by any page. It gets tricky, though, because the engines for both can't always see styles that need to be present, particularly those triggered by scripts that swap out styles for menu collapses and the like. We also use intersection observer scripts to only load images when they're close to the visible area of the viewport as the viewer scrolls.

I don't think there's a single solution for this that will fit everyone's needs.

**Comment by BohemiansThemes** [comment]
Thanks for reply. 

I'm using the parent theme and I'm curious if  there is another file than "enqueue.php" from "inc folder", to work on? I've tried some scripts there but no improvements. 

Can you help me with an example?

**Comment by axlright** [comment]
I'd use the child theme for this, because if you modify the parent theme, your customizations will get overwritten each time you update the theme.

Can you give example of what you're looking to accomplish?

**Comment by BohemiansThemes** [comment]
I want to add "async" and "defer" to all my enqueued scripts and maybe in this way I will improve the speed of the theme, which is my final goal.

**Comment by Thomas-A-Reinert** [comment]
It just depends on which tools you use for testing and from WHERE you test. Usually my - heavily customized themes! - get a 95/95 score from a location near the server without any caching etc.

If you put Autoptimize/W3TC into place you´ll get even better results.

I´ll close this issue anyway, because that´s not really an UnderStrap, but a general performance related issue.
