### ISSUE TITLE
Missing file '/js/customizer.js' still being enqueued by customizer.php

### ISSUE THREAD

**Issue by dancriel** [understrap/understrap#947]
/inc/customizer.php is enqueueing /js/customizer.js even though that JS file was removed from /src several releases ago. Seems like the enqueue function should be dropped from customizer.php. Although I did see some closed tickets related to this JS file, I could not find a reason why the customizer.php file is still trying to enqueue that JS.

**Comment by m4v1** [comment]
customizer.js has been re-added with this commit https://github.com/understrap/understrap/commit/01af1b4da5b52fe8a38f671d5efe4d9593eb7558

**Comment by Thomas-A-Reinert** [comment]
Okay, I can confirm that ./inc/customizer.php is in fact enqueueing ./js/customizer.js .
Seems that I´m kinda missing out the problem at all.

- I cannot see any console errors.
- I don´t know what it´s good for - while you seem to know that.
- It doesn´t seem to do any harm..

I´d like to come up with a quick solution but it seems I´m missing the big picture. If you could get me up to date what the problem is, that would be nice.

Thanks in advance.

**Comment by m4v1** [comment]
Sorry I wasn't  too clear in my previous message, customizer was removed then reintroduced, but at this stage there is no issue because the file /js/customizer.js is back in place.
So I think this can be closed.

**Comment by Thomas-A-Reinert** [comment]
Okay, thanks for keeping me posted, @m4v1 .
