### ISSUE TITLE
Find and replace of understrap breaks theme styles

### ISSUE THREAD

**Issue by markfenske84** [understrap/understrap#948]
I'm attempting to rename all the references to understrap in the theme files and following the _s documentation to do so since thats what it's based off of ([link](https://themeshaper.com/2012/02/21/getting-started-with-the-underscores-theme/)).  Doing a search and replace of:

' understrap'
'understrap_'
'understrap'

and replacing with my own theme name breaks the site styles and I'm not entirely sure why.  Is there any reason why with would work for vanilla underscore but not understrap or is there documentation on how to properly do this with understrap?

**Comment by zachatkinson** [comment]
Are you using a child theme?

**Comment by noelspringer** [comment]
@markfenske84 did  you also change the Text Domain in `style.css` and rename the `understrap` theme folder?

**Comment by Thomas-A-Reinert** [comment]
Seems like a "not well-refined-search-and-replace" to me. No offence intended, @markfenske84 . Since you didn´t get back for more than a month to the people trying to help you, I guess you figured out the problem on your own.

So I´ll close that issue due to housekeeping. Please reopen if the problem persistsl.
