### ISSUE TITLE
Add minicart on header

### ISSUE THREAD

**Issue by PetteriSeoka** [understrap/understrap#952]
Hi,

I apologise beforehand if my question is too basic. 

How do I add the Woocommerce minicart to the header?

Thanks in advance

**Comment by noelspringer** [comment]
I've used a plugin to do that [https://wordpress.org/plugins/woocommerce-menu-bar-cart/](https://wordpress.org/plugins/woocommerce-menu-bar-cart/).

**Comment by 0dp** [comment]
is this resolved @PetteriSeoka

**Comment by PetteriSeoka** [comment]
I used this plugin https://wordpress.org/plugins/side-cart-woocommerce/, which works great.

**Comment by 0dp** [comment]
@PetteriSeoka awesome, glad to hear.

Do you mind closing the issue if it's resolved

**Comment by Thomas-A-Reinert** [comment]
Hi @PetteriSeoka sorry for jumping in so late, just got aware of this topic.

Usually I don´t like solving every single function/behaviour via a plugin. Because..

1. It´s becoming a mess of a heap of plugins, especially when using WooCommerce.
2. If the plugin is no longer supported how to explain to the customer?
3. I lack control of how things are being handled.

So I prefer using functions instead. Usually for WooCommerce I add a `custom_woocommerce.php` in  `./inc/` folder instead of adding up to `functions.php`, add all my custom WC-functions there and include those via functions php. But that´s up to you - the outcome is going to be the same.

Instead of giving you a super-customized (and not so well commented ;) ) solution I´d rather give you a link to [some basic tutorial on how to achieve the same](https://slocumthemes.com/2015/06/how-to-display-shopping-cart-details-wordpress-menu/) - just strip the "Easy Digital Downloads" part if you don´t need it. You could add a lot of stuff more to it like link to the user profile or whatever.

Besides I usually use a custom menu for that so please note that you may need to adjust line 15 where it says `theme_location === 'top_nav'` to match the ID of the menu you´ll want to use.
