### ISSUE TITLE
Dependencies Security Issues

### ISSUE THREAD

**Issue by RenaudGagne** [understrap/understrap#959]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

Windows 10

---

# Issue Overview for Bugreports

## Steps to reproduce?

npm install

## *Who* is the bug affecting?

All users 

## *What* is affected by this bug?

Understrap dependencies

## *Where* on the platform does it happen?

In the command line

### Other Comments

When installing, npm is warning me that there it has found 17 vulnerabilities (3 low, 6 moderate, 8 high).

Do you have a plan to update or change some of the dependencies behind understrap?

**Comment by RenaudGagne** [comment]
so...you don't care guys?

**Comment by Thomas-A-Reinert** [comment]
Hi @RenaudGagne - sorry that noone replied so far.

Yes we DO care about security problems.
But honestly, they do currently occur just on the developers side - that means: locally.
That doesn´t make it perfect, but as node.js won´t run on the server that makes it kinda neglectible.

Anyway. I _do_ feel with you that it just doesn´t feel good to install anything that comes up with a bunch of security issues that one cannot evaluate.

As long as the "Live environment" (Server / PHP / HTML / CSS / Javascript) is not affected there should be no problem - and we´re watching exactly that pretty carefully. 

I´m closing that issue due to housekeeping. If you have any updates, don´t feel satisfied with my answer, please feel free to re-open that issue, okay?
