### ISSUE TITLE
Convert Bootstrap 4 Slider to show images as Div backgrounds

### ISSUE THREAD

**Issue by sayayinR** [understrap/understrap#962]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [X ] I need help

Hi Guys,
I need help with something. I will like the slider to show images as backgrounds instead of img tags. Wordpress is not my specialty and not sure if this is even possible. I was hoping I could just find the file and modify html and PHP  to render the image path in a style attribute on div instead but I have not been able to find how the html markup is being generated.
I might even hire someone to do this for me but wanted to see if someone can atleast tell me what will it take to do so. Will it require more of PHP development or front end or both. I will appreciate any guidance.

Thank you.

**Comment by sayayinR** [comment]
So I hired someone and they took care of this with jQuery which I could have done myself. Can someone advise what should be the best way to handle this. I thought they will handle this with php on the server and not on the client side. I have asked them the same, let's see what they say.

**Comment by Thomas-A-Reinert** [comment]
This can be achieved in so numerous ways that there is not that ONE answer. If you yourself could have achieved it using jQuery, I´m asking myself why you just haven´t done it like so but hired someone to do it? 

Anyway: You´d need to use Javascript no matter how for the frontend display. You´ll also need to code something to supply the data to JS via PHP, JSON or whatever. If you´re going to use vanilla Javascript, built-in jQuery or Angular/React/Vue.js - that´s totally up to you. They´re all going to do the job. I realized all of them according to the individual customers preferences.

As almost 99% of my customers want to use an overlay with Headline, Subtext and Button for ANY individual slide, I usually use Advanced Custom Fields (ACF) to allow them to add above mentioned. Sidenote: The "Repeater"-Field is needed for that, so that´s going to need the commercial version. You won´t get around using the free version. Anyway, the same can be achieved using a free, non-commercial, but not SO easy to dive-into alternative like [CMB2](https://github.com/CMB2/CMB2).

I used to use https://www.jquery-backstretch.com/ for that when the requirements allowed it. That´s an easy to use jQuery plugin. But honestly, there are smarter solutions, especially if you want to display a static image first-hand that gets loaded and displayed without Javascript and make a difference between mobile/desktop and/or need to performance-optimize your application.

There are so many variables for your possible (not really declared) fulfillment, that I didn´t jump in first-place to give you the "_one possible solution_". 

I just jump in to...
a.) note that this is not any kind of an understrap problem.
b.) to plead for the guys who did what you seemingly were not able to achieve. As long as it does what it should do - it´s all good as long as you didn´t EXACTLY define how you wanted it to be done.
c.) close this topic, because it´s not really understrap related and/or a problem with the software at all.

In case you need an ACF/CMB2 solution drop me a note and we´ll find a way.
