### ISSUE TITLE
Outdated Theme - Theme Update error on Woocommerce 3.6.2 

### ISSUE THREAD

**Issue by anasiqbalkhan** [understrap/understrap#968]
I am getting this error: Please update theme

Your theme (UnderStrap) contains outdated copies of some WooCommerce template files. These files may need updating to ensure they are compatible with the current version of WooCommerce. Suggestions to fix this:

Update your theme to the latest version. If no update is available contact your theme author asking about compatibility with the current WooCommerce version.
If you copied over a template file to change something, then you will need to copy the new version of the template and apply your changes again.

Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 5.1.1
  - **WooCommerce Version:** 3.6.2

**Comment by noelspringer** [comment]
Hi @anasiqbalkhan what version of UnderStrap are you using?

**Comment by anasiqbalkhan** [comment]
> Hi @anasiqbalkhan what version of UnderStrap are you using?

UnderStrapVersion: 0.9.1

**Comment by noelspringer** [comment]
Hi @anasiqbalkhan the template updates are incorporated into the master branch.

Download the zip file of the master branch and use that to replace your  0.9.1 version (unless you've made changes to the UnderStrap files). 

Typically you will need to rename the unpacked folder to `understrap`.

**Comment by noelspringer** [comment]
Hi @anasiqbalkhan in case you haven't noticed yet the latest version of UnderStrap (0.9.3) is also available from [WordPress.org](https://wordpress.org/themes/understrap/) now.

**Comment by Thomas-A-Reinert** [comment]
Does any of this SOLVE the problem? As there were no updates to the issue about a month ago and a possible solution posted, I´ll close that issue due to housekeeping.

Feel free to reopen if the problem persists. And even better: PLEASE confirm that this issue was resolved!

Thanks

**Comment by noelspringer** [comment]
Hi Thomas this issue was resolved with the release of Understrap 0.9.3 which incorporated the latest Woocommerce template changes.

**Comment by Thomas-A-Reinert** [comment]
Thanks for the confirmation, Noel!

**Comment by noelspringer** [comment]
You're welcome Thomas :-).

**Comment by Thomas-A-Reinert** [comment]
No, really. I appreciate your involvement.

**Comment by alexhessrobinson** [comment]
As WooCommerce updates their template files, some of the templates that correspond with the Understrap WooCommerce files fall out of date. Following these steps helped me resolve the issue recently. Make sure you make backups before running through these steps. [Fixing Outdated WooCommerce Templates](https://docs.woocommerce.com/document/fix-outdated-templates-woocommerce/)

**Comment by noelspringer** [comment]
Hi Thomas, this is the process I use for updating Woocommerce templates ( [Fixing Outdated WooCommerce Templates](https://docs.woocommerce.com/document/fix-outdated-templates-woocommerce/) ). Each new release of Woocommerce is checked for required template updates which are usually completed within 48 hours and a pull request submitted.

There is an open pull request #1080 for the Woocommerce 3.7.0 update. An earlier pull request (August) for the same update failed because I had already deleted the branch when I saw that @UnderstrapFramework had approved the request and I assumed (incorrectly) that also meant it was merged. I needed to refork UnderStrap.

For other users of UnderStrap who are installing from WordPress.org, a new UnderStrap point release is required [as mentioned here](https://github.com/understrap/understrap/issues/1071#issuecomment-560056191).

cc @UnderstrapFramework
