### ISSUE TITLE
Style Sheets not loading Child-theme/src/sass/bootstrap-4/_xxxxxx.scss

### ISSUE THREAD

**Issue by KmayZOMBY** [understrap/understrap#971]
Designing my child theme locally, I am receiving these warnings after each re-load on my browser:
It reads at the bottom of the page with a yellow warning sign
**"Style Sheet could not be loaded. http://xxxxx/wp-content/themes/understrap-child-master/src/sass/boostrap4/_xxxxxxxx.scss"**
The **_xxxxxx.scss** refer to ALL files in that folder. It lists them all as a warning and won't load.
I have recently updated the understrap 0.9.2 this morning so I am not sure if this is the cause.

Thanks

**Comment by Thomas-A-Reinert** [comment]
Hi KmayZOMBY, I can´t tell if it´s causing it, but I never had that problem so..

Your parent themes name should be "_understrap_" (without "_-master_"), your child-themes name should be "_understrap-child_" (without "_-master_"). Please rename both and try again.

**Comment by KmayZOMBY** [comment]
Thanks Thomas-A-Reinert,
I tried to rename my child folder without the master word and it reset all my changes. When renaming it back, all changes are back.
But amazingly, the error I was referring to before is still there 🗡

**Comment by holger1411** [comment]
Seems you try to load a .scss source file.
The base child theme did not do that:
https://github.com/understrap/understrap-child/blob/master/functions.php
Pls check if there are manual changes to this file above (understrap-child/functions.php)

**Comment by KmayZOMBY** [comment]
Hi holger1411 & thanks
Yes, my file is exactly the same. I just added this after all that code:

// NAV MENUS
function understrap_nav_custom_menus() {
    register_nav_menu ('left-menu', __('Left Nav Menu'));
    register_nav_menu ('right-menu', __('Right Nav Menu'));
    register_nav_menu ('mobile-menu', __('Mobile Nav Menu'));
    register_nav_menu ('footer-menu', __('Footer Nav Menu'));
}
add_action( 'init','understrap_nav_custom_menus' );

But it was working fine for weeks before this warning. from today.

**Comment by Thomas-A-Reinert** [comment]
@KmayZOMBY I ´m going to close that issue for housekeeping due to the following facts:

- No feedback within about a month
- A child-theme issue that was posted to the parent theme issue tracker.

Anyway. I see some problems that may solve your issue:
- WHY is your browser moaning about that it cannot load any *.scss files? it should never do that! It should load the generated css-files NOT the scss files that a browser can´t process anyway?
- WHY is your browser moaning that it cannot load files from "`http://xxxxx/wp-content/themes/understrap-child-master/src/sass/boostrap4/_xxxxxxxx.scss`" ?! It should never ever go to that path! It should get the css from "`http://xxxxx/wp-content/themes/understrap-child-master/css/child-theme.min.css`" according to your setup.
- `http://xxxxx/wp-content/themes/understrap-child-master/src/sass/_**boostrap4**_/_xxxxxxxx.scss` may be another problem?!
There is no "boostrap" but a "bootstrap".

A lot of errors that - sorry! - I assume that are plain user problems. Please iron those out and I´m sure things will just get along fine.
