### ISSUE TITLE
can someone tell me ideally how I would change footer color and btn color?

### ISSUE THREAD

**Issue by redknite** [understrap/understrap#981]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

 ---

I am running understrap and a child theme on a local dev.  Everything is going great.  I have my node watching and all is sweet sailing.

I've figured out that if I add 

css to my childtheme/sass/theme/_child_theme.scss while running "gulp watch" changes are updated.  whooo hoo!

The question I have is what is the suggested method to change for instance...

Button font color:
right now I just added 
`.btn {
  color:white;
  }`

to childtheme/sass/theme/_child_theme.scss  But it seems this MAY not be what I'm supposed to do.

and footer background color:

right now it's set to a random color, but I want it to be set to my $secondary color.  I'm not sure where to start with this.

**Comment by Thomas-A-Reinert** [comment]
Hi @redknite , hope I got your question/s right...

For changing your footer open up your developer tools (F12), choose inspect, click the footer. That should show you that it uses the IDs `#wrapper-footer` and  `#wrapper-footer-full`, if I´m not all wrong (Currently inspecting a heavily customized theme, I have no stock-install at hand right now)
So if you change your childtheme SCSS to 
```
#wrapper-footer, #wrapper-footer-full   {
    background-color: $secondary;
}
```
That should do the job.

According buttons.. It´s not too smart to adjust ANY button (`.btn `Class) to just a single color. See https://getbootstrap.com/docs/4.0/components/buttons/ for that. Not all foreground colors will work with all of the supplied background colors.
So it would be smarter to adjust the foreground color of styles like `.btn-primary`, `.btn-danger`, `.btn-light` or whatsoever to a specific to the according background.

So go for the second parameter, not the first one. The first defines a button (..), the second it´s styling.

Just as an example: If you´d want to change the style of the "LINK" Button, i´d do it like that:
```
.btn-link {
  color: $white;
  background-color: $whatever;
}
```

I´ll close that issue right now, because it´s not really an UnderStrap related problem, but more a Bootstrap/CSS/SCSS/Customization problem. If you have any questions though - feel free to respond and I´ll try to help anyway, okay?

**Comment by redknite** [comment]
Wow!  Not only a complete response, but quick and concise.  Thank you very much.  So the best place to put these changes IS in my childtheme/sass/theme/_child_theme.scss though?  Or is there somewhere more appropriate?

**Comment by Thomas-A-Reinert** [comment]
No problem, you´re welcome.

Well it depends which kind of button you´d want to change. Take a look on the link I provided above. Bootstrap4 buttons are not meant to be used with the `.btn` class alone but with the second which provides its colors. That´s what is called "[atomic design](http://atomicdesign.bradfrost.com/)".

It´s totally up to you to change the generic `.btn `class or add others suiting your own needs like I usually do to realize [ghost-buttons](https://uxmag.com/articles/15-ethereal-examples-of-ghost-buttons-in-action) with a custom `.btn-ghost` class which I then use like that:
`<a href="{link}"  role="button" class="btn btn-dark">Click me!</a>`

I just override the generic `.btn` class to get rid of the rounded corners because I usually don´t want to have ANY rounded buttons at all.

Yes, it´s totally okay to put your overrides/additions into _child_theme.scss . It will work.

..although it may not be the smartest way according to atomic design recommendations. Take a peep at Bootstraps own structure where there is a single file for each content element like text, buttons, tables and whatsoever. I usually handle my child-theme SCSS the same way - using it as a starter to import the "atoms".

Advantage: I have a library of single content-modules I can easily copy and import into any new project, making a good amount of my projects more or less just "recycling" than coding everything anew each time.

I´m lazy - that´s why I´m a coder ;)
