### ISSUE TITLE
Tooltip how to insert

### ISSUE THREAD

**Issue by webstoria** [understrap/understrap#985]
I've a problem with tooltips not display

I enqueue file with my own scripts in enqueue.php file
wp_enqueue_script( 'understrap-my-scripts', get_template_directory_uri() . '/js/scripts.js');

In my scripts.js file is 

$(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

I want test it on my page insert simple code from bootstrap documentation 

<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
  Tooltip on top
</button>

and nothing 

What I was doing wrong 

## Issue is about..
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2
  - **OS Version:** [Windows 7]
  - **Browser:** [ all ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery]

**Comment by axlright** [comment]
Do you see the script loaded on the frontend page?

This appears to be more of a general WordPress and script issue. It doesn't appear that anything specific to the UnderStrap theme is causing a problem.

If you can provide more information specific to the UnderStrap theme, that would be helpful.

**Comment by webstoria** [comment]
My WordPress is 5.2.1 and Understrao theme is 0.9.3
This is what i see in header in source view:

<script type='text/javascript' src='//localhost:3000/wordpress/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp'></script>
--
  | <script type='text/javascript' src='//localhost:3000/wordpress/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
  | <script type='text/javascript' src='//localhost:3000/wordpress/wp-content/themes/understrap/js/scripts.js?ver=5.2.1'></script>
  Last one is my js script

This is what I write in js script

$(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

Also I have front-page.php

and there is code

<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>">
  Tooltip with HTML
</button>

**Comment by Thomas-A-Reinert** [comment]
There are so many possible problems, that the question cannot be answered with a definitive solution without having a look at your code. Some assumptions though.

1. It´s not the best way to use `wp_enqueue_script( 'understrap-my-scripts', get_template_directory_uri() . '/js/scripts.js');` for enqueuing a script. Please see https://stackoverflow.com/questions/31797203/whats-the-difference-between-get-stylesheet-directory-uri-and-get-template-di for better solutions. In short. I´d suggest using `get_stylesheet_directory_uri()` instead of `get_template_directory_uri()` because it adresses the CURRENT themes dir - be it a child or parent theme.
2. You should really get used to the developer tools/console. In Chrome/FF/IE hit F12 and take a peep at the "console" tab.
3. I´d swear it says something like `Uncaught TypeError: $ is not a function` . The reason is that WP doesn´t support the factory function $() because it uses "no-conflict mode".

There are several solutions for this.
- Replace every occurence of "$" with "jQuery". See example N°1.
- You can use an anonymous function to pass every occurence of "$" to jQuery. See example N°2.
- There are even more but I that´s too much now.. ;)

Example N°1:
```javascript
jQuery(function () {
  jQuery('[data-toggle="tooltip"]').tooltip()
})
```
Example N°2:
```javascript
(function($) {
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
})(jQuery);
```
I´d suggest using N°2, because you can just copy and paste all your jQuery code into the `(function($) { })(jQuery);` function whithtout changing it and you´re good to go.

Sidenote: this is a generic WordPress problem, not an understrap issue.

**Comment by webstoria** [comment]
Ok thx for sugestions I look up in stackoverflow

**Comment by Thomas-A-Reinert** [comment]
Did you actually try any of my solutions? For simplicities sake I just wrote the Javascript (Example N°1) in the footer.php file and everything shows up as expected:

![image](https://user-images.githubusercontent.com/5886977/59152171-6135cf80-8a3f-11e9-9dff-1dc763d6eba4.png)
