### ISSUE TITLE
theme.min.js with no effect

### ISSUE THREAD

**Issue by Tartamata** [understrap/understrap#999]
Hello guys,
My problem is a bit strange
I just started developing a new theme using understrap but i noticed that theme.min.js has no effect, even if it's dequeued the theme keeps working fine.
Any idea ?
## Please tell us about your environment:

  - **WordPress Version:** 5.2.2
  - **OS Version:** MacOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]
---

**Comment by Thomas-A-Reinert** [comment]
Hi @Tartamata .. Please let´s clarify some things..

1.) Yes, the theme itself will just keep working fine without any JS at all.
2.) Why is it included? Because some Bootstrap function _need_ it. See https://getbootstrap.com/docs/4.1/getting-started/javascript/
3.) What kinda features need JS? Not a complete list, just an excerpt: Tooltips, any kind of "toggles", submenues, modals etc.

As we try to support any BS4 feature it is included by default. Please check BS4 documentation on what is really _needed_ and what not. That´s really not an UnderStrap issue, so i´m going to close this one.

Feel free to dequeue and see how far you can go without. That´s up to you. ;)
